const Map<String, String> enScreensStrings = {
  'wallet.title': 'Wallet',
  'wallet.totalBalance': 'Total balance',
  'wallet.demoNotice':
      'Demo wallet — no real keys are generated or stored in this beta.',
  'wallet.allocations': 'Allocations',
  'wallet.activity': 'Transactions',
  'wallet.receive': 'Receive',
  'wallet.send': 'Send',
  'wallet.unallocated': 'Unallocated',
  'wallet.noAllocations': 'No allocations yet',
  'wallet.noAllocationsBody': 'Hold MPC against a live project to see it here.',
  'wallet.noTransactions': 'No transactions yet',
  'wallet.noTransactionsBody': 'Transactions will appear here.',
  'wallet.loading.title': 'Loading wallet',
  'wallet.loading.body': 'Checking balances and recent activity…',
  'wallet.tryAgain': 'Try again',
  'wallet.unavailable': 'Wallet unavailable',
  'wallet.unavailableBody':
      "We couldn't load balances. Your wallet remains protected.",
  'wallet.addressCopied': 'Address copied',
  'wallet.transfersLater': 'Transfers land in a later milestone.',

  'earn.title': 'Earn',
  'earn.gatedBanner':
      'Earn capabilities are planned and gated until listing and eligibility requirements are confirmed.',
  'earn.status.planned': 'Planned',
  'earn.rateLabel': 'Reward rate',
  'earn.ratePending': 'Announced at listing',
  'earn.notify': 'Notify me',
  'earn.notifyToast': 'We’ll notify you when this opens.',
  'earn.staking.title': 'Staking',
  'earn.staking.body':
      'Lock MPC to back mining-asset issuance. Reward terms are published when the program opens at listing.',
  'earn.farming.title': 'Farming',
  'earn.farming.body':
      'Provide MPC liquidity once the token lists, and earn from trading activity. Terms are published at listing.',
  'earn.whyGated': 'Why not yet?',
  'earn.gate.kyc.title': 'Identity verification (KYC)',
  'earn.gate.kyc.body':
      'MPC issuance is designed on ERC-3643, so earning will require a verified identity.',
  'earn.gate.listing.title': 'Public listing',
  'earn.gate.listing.body': 'Reward rates and pools are set when MPC lists.',

  'settings.title': 'Settings',
  'settings.profile': 'Profile',
  'settings.language': 'Language',
  'settings.appearance': 'Appearance',
  'settings.section.preferences': 'Preferences',
  'settings.section.wallet': 'Wallet & Security',
  'settings.section.appInfo': 'Support & legal',
  'settings.needHelp': 'Need help?',
  'settings.helpSupport': 'Help & support',
  'settings.notify.label': 'Notifications',
  'settings.notify.manage': 'Manage',
  'settings.notify.title': 'Notifications',
  'settings.notify.transactions': 'Transaction updates',
  'settings.notify.transactionsBody':
      'Status changes for sent and received MPC.',
  'settings.notify.security': 'Security alerts',
  'settings.notify.securityBody': 'PIN, recovery and device-security events.',
  'settings.notify.projects': 'Project updates',
  'settings.notify.projectsBody':
      'Material status changes for followed projects.',
  'settings.security': 'Security',
  'settings.pinBiometrics': 'PIN & biometrics',
  'settings.backup': 'Backup & recovery',
  'settings.verifyBackup': 'Verify backup',
  'settings.about': 'About MPC',
  'settings.privacyNotices': 'Privacy & open-source notices',
  'settings.rateUs': 'Rate us',
  'settings.review': 'Review',
  'settings.removeWallet': 'Remove wallet from this device',
  'lang.chooseLanguage': 'Choose language',
  'lang.applyLanguage': 'Apply language',
  'lang.selected': 'Selected',

  'wallet.create.title': 'Create wallet',
  'wallet.create.step0.header': 'A wallet only you control',
  'wallet.create.step0.body':
      'MPC creates your wallet on this device. Your recovery phrase is the only way to restore access if this device is lost.',
  'wallet.create.step0.holdKeys': 'You hold the keys',
  'wallet.create.step0.holdKeysBody':
      'MPC cannot recover or reset your phrase.',
  'wallet.create.step0.backupOffline': 'Back it up offline',
  'wallet.create.step0.backupOfflineBody':
      'Write the words down and keep them private.',
  'wallet.create.step0.protectDevice': 'Protect this device',
  'wallet.create.step0.protectDeviceBody':
      'Set a PIN and optionally use biometrics.',
  'wallet.create.step0.button': 'Create new wallet',
  'wallet.create.step1.header': 'Back up your recovery phrase',
  'wallet.create.step1.body': 'Write these 12 words down in order.',
  'wallet.create.step1.phraseLabel': 'Recovery phrase',
  'wallet.create.step1.saved': 'I saved these words',
  'wallet.create.step1.download': 'Download',
  'wallet.create.step1.copy': 'Copy codes',
  'wallet.create.step1.warning':
      'Never share these words with anyone. MPC support will never ask for your recovery phrase.',
  'wallet.create.step1.copied':
      'Recovery phrase copied. Clipboard clears in 30s.',
  'wallet.create.step1.saveDigital': 'Save digitally?',
  'wallet.create.step1.saveDigitalBody':
      'Any app or cloud service you save this to can read your recovery phrase. Writing the words down offline is safer.',
  'wallet.create.step1.saveCancel': 'Cancel',
  'wallet.create.step1.saveContinue': 'Continue',
  'wallet.create.step2.header': 'Verify your backup',
  'wallet.create.step2.body':
      'Select the requested words to confirm your backup.',
  'wallet.create.step2.button': 'Verify backup',
  'wallet.create.step2.mismatchTitle': "The words didn't match",
  'wallet.create.step2.mismatchBody':
      "Check your recovery phrase and try again. We'll ask for different words next time.",
  'wallet.create.step2.wordLabel': 'Word #{n}',
  'wallet.create.step2.wordHint': 'Enter word #{n}',
  'wallet.create.pin.createTitle': 'Create an app PIN',
  'wallet.create.pin.createBody': 'Use this PIN to unlock MPC on this device.',
  'wallet.create.pin.confirmTitle': 'Confirm your PIN',
  'wallet.create.pin.confirmBody': 'Enter the same 6-digit PIN again.',
  'wallet.create.pin.hint': 'Your PIN protects this device only.',
  'wallet.create.pin.safeTitle': 'Your wallet is still safe',
  'wallet.create.pin.safeBody':
      'Nothing has been saved or changed. Re-enter the PIN to continue.',
  'wallet.create.pin.continue': 'Continue',
  'wallet.create.pin.reEnter': 'Re-enter PIN',
  'wallet.create.pin.confirm': 'Confirm PIN',
  'wallet.create.pin.mismatch': 'PINs do not match. Try again.',
  'wallet.create.biometric.title': 'Protect your wallet',
  'wallet.create.biometric.body':
      'Adding biometric security will ensure that you are the only one who can access your wallet',
  'wallet.create.biometric.faceId': 'Face ID / Touch ID',
  'wallet.create.biometric.recommended': 'Recommended',
  'wallet.create.biometric.finish': 'Finish setup',
  'wallet.create.securing.title': 'Creating your wallet',
  'wallet.create.securing.body': 'Adding a new MPC wallet…',
  'wallet.create.securing.keepOpen': 'Keep MPC open',
  'wallet.create.securing.keepOpenBody':
      'Do not close the app while this security check completes.',
  'wallet.create.securing.inProgress': 'Securing wallet…',
  'wallet.create.done.title': 'Wallet created',
  'wallet.create.done.body': 'Your wallet is protected and ready to use.',
  'wallet.create.done.open': 'Open wallet',

  'wallet.import.syncing.title': 'Importing your wallet',
  'wallet.import.syncing.body': 'Securing this device and syncing wallet data…',

  'wallet.secure.done.title': 'Wallet secured',
  'wallet.secure.done.body':
      'Your wallet is protected by this device and your new PIN.',

  'wallet.secure.failed.title': "We couldn't secure the wallet",
  'wallet.secure.failed.body': 'No wallet data was saved on this device.',
  'wallet.secure.failed.deviceTitle': 'Device security unavailable',
  'wallet.secure.failed.deviceBody':
      'Check storage and device security settings, then try again.',
  'wallet.secure.failed.retry': 'Try again',
  'wallet.secure.failed.returnToWelcome': 'Return to welcome',

  'wallet.import.title': 'Import wallet',
  'wallet.import.secure': 'Secure wallet',
  'wallet.import.step0.header': 'Restore your existing wallet',
  'wallet.import.step0.body': 'Before entering your recovery phrase:',
  'wallet.import.step0.keepPrivate': 'Keep it private',
  'wallet.import.step0.keepPrivateBody':
      'Make sure nobody can see your screen.',
  'wallet.import.step0.enterOnly': 'Entered only here',
  'wallet.import.step0.enterOnlyBody': 'Never send your phrase to support.',
  'wallet.import.step0.stored': 'Stored securely',
  'wallet.import.step0.storedBody':
      'MPC protects access with your device and PIN.',
  'wallet.import.step0.understand': 'I understand',
  'wallet.import.phrase.header': 'Enter recovery phrase',
  'wallet.import.phrase.body':
      'Paste or type your recovery words in the correct order.',
  'wallet.import.phrase.label': 'Recovery phrase',
  'wallet.import.phrase.hint': 'Paste or type your recovery words',
  'wallet.import.phrase.support':
      'MPC support will never ask for your recovery phrase.',
  'wallet.import.phrase.errorEmpty': 'Add your recovery phrase to continue.',
  'wallet.import.phrase.errorInvalid':
      'That recovery phrase is not valid. Check the words and their order.',
  'wallet.import.phrase.review': 'Review wallet',
  'wallet.import.biometric.finish': 'Finish import',
  'wallet.import.address.header': 'Review wallet',
  'wallet.import.address.body': 'Confirm the wallet address before continuing.',
  'wallet.import.address.label': 'WALLET ADDRESS',
  'wallet.import.address.confirm': 'This is my wallet',
  'wallet.import.ready.title': 'Wallet imported',
  'wallet.import.ready.body': 'Your existing wallet is ready on this device.',
  'wallet.import.ready.securityComplete': 'Security complete',
  'wallet.import.ready.securityBody':
      'Your recovery phrase remains the only way to restore access on another device.',
  'wallet.import.ready.open': 'Open wallet',

  'wallet.secure.failed': "We couldn't secure the wallet",
  'wallet.secure.noData': 'No wallet data was saved on this device.',
  'wallet.secure.unavailable': 'Device security unavailable',
  'wallet.secure.checkSettings':
      'Check storage and device security settings, then try again.',
  'wallet.secure.retry': 'Try again',
  'wallet.secure.returnWelcome': 'Return to welcome',

  'wallet.phrase.words': '{count} words',

  'theme.system': 'System',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.apply': 'Apply theme',
  'profile.title': 'Profile',
  'profile.details': 'Account details',
  'profile.walletAddress': 'Address',

  'unlock.welcomeBack': 'Welcome back',
  'unlock.enterPin': 'Enter your PIN to unlock your wallet.',
  'unlock.forgotPin': 'Forgot PIN? Restore wallet',
  'unlock.unlock': 'Unlock wallet',
  'unlock.unlocking': 'Unlocking…',
  'unlock.useBiometrics': 'Use biometrics',
  'unlock.newToMpc': 'New to MPC? ',
  'unlock.pinPrivacy': 'Your PIN never leaves this device.',
  'unlock.biometricSheet.title': 'Unlock MPC',
  'unlock.biometricSheet.body': 'Confirm with Touch ID or Face ID',
  'unlock.restore.title': 'Restore wallet?',
  'unlock.restore.body':
      'Your device PIN cannot recover your wallet. Continue only if you have your recovery phrase.',

  'common.cancel': 'Cancel',
  'common.done': 'Done',
  'common.continueBtn': 'Continue',
  'common.on': 'On',
  'common.off': 'Off',
  'common.thisDevice': 'This device',
  'common.gotIt': 'Got it!',
  'common.pin.incomplete': 'Enter all 6 digits.',
  'common.pin.incorrect': 'Incorrect PIN. Try again.',
  'common.inProgress': 'In progress',
  'receive.title': 'Receive {asset}',
  'receive.unavailable': 'Wallet address unavailable',
  'receive.warning':
      'Only send {asset} and supported BNB Smart Chain assets to this address.',
  'receive.copy': 'Copy address',
  'receive.share': 'Share address',
  'receive.shareTemplate':
      'My {asset} wallet address on BNB Smart Chain:\n{address}',
  'receive.wrongNetwork':
      'Assets sent on another network may be permanently lost.',
  'send.title': 'Send MPC',
  'send.reviewShort': 'Send',
  'send.pin.title': 'Confirm with PIN',
  'send.unavailableBody': 'Reload your wallet before sending.',
  'send.recipient': 'Recipient address',
  'send.recipientHint': 'Paste a valid wallet address',
  'send.paste': 'PASTE',
  'send.amount': 'Amount',
  'send.useMax': 'Use maximum',
  'send.available': '{amount} available',
  'send.safety':
      'Confirm the recipient and network carefully. Blockchain transactions cannot be reversed.',
  'send.review.cta': 'Review transaction',
  'send.review.sending': 'You\'re sending',
  'send.review.to': 'To',
  'send.review.copyRecipient': 'Copy recipient address',
  'send.review.fee': 'Network fee',
  'send.review.feeValue': '~{fee} BNB',
  'send.review.notEnoughBnb': 'Not enough BNB',
  'send.review.note':
      'This transaction cannot be changed or cancelled after submission.',
  'send.review.confirm': 'Confirm and continue',
  'send.review.edit': 'Edit transaction',
  'send.amountMpc': '{amount} MPC',
  'send.gas.title': 'BNB needed for network fee',
  'send.gas.body':
      'This transfer needs about {fee} BNB. Your wallet has {bnb} BNB.',
  'send.gas.needed': 'Needed',
  'send.gas.note': 'Your MPC balance will not be used for this fee.',
  'send.gas.receive': 'Receive BNB',
  'send.gasInfo.title': 'Estimated network fees',
  'send.gasInfo.body': 'This is the BNB Smart Chain gas fee for the transfer.',
  'send.pin.prompt': 'Enter your 6-digit app PIN',
  'send.pin.confirm': 'This confirms that it is you sending {amount} MPC.',
  'send.pin.hint': 'Enter your app pin',
  'send.processing.title': 'Processing transaction',
  'send.processing.body': 'Keep MPC open while this completes.',
  'send.success.title': 'Transaction Submitted',
  'send.success.headline': 'MPC sent',
  'send.success.body': '{amount} MPC was submitted to {address}.',
  'send.success.status': 'Status',
  'send.success.pending': 'Pending confirmation',
  'send.success.view': 'View transaction',
  'send.success.back': 'Back to wallet',
  'send.failure.title': 'Transaction not sent',
  'send.failure.body':
      'Your balance has not changed. Check your connection and try again.',
  'send.failure.retry': 'Try again',
  'send.failure.cancel': 'Cancel transfer',
  'send.error.address': 'Enter a valid BNB Smart Chain address.',
  'send.error.self': 'This is your own wallet address.',
  'send.error.zero': 'Enter an amount greater than zero.',
  'send.error.balance': 'You only have {amount} unallocated MPC.',
  'tx.details.title': 'Transaction details',
  'tx.details.status': 'Status',
  'tx.details.from': 'From',
  'tx.details.to': 'To',
  'tx.details.vault': 'Project vault',
  'tx.details.date': 'Date',
  'tx.details.hash': 'Transaction hash',
  'tx.status.submitted': 'Submitted',
  'tx.status.pending': 'Pending',
  'tx.status.confirmed': 'Confirmed',

  'settings.remove.title': 'Remove wallet?',
  'settings.remove.body':
      'This removes wallet access and the PIN from this device. You will need your recovery phrase to restore the wallet.',
  'settings.remove.type': 'Type REMOVE to continue.',
  'settings.remove.keep': 'Keep wallet',
  'settings.remove.confirm': 'Remove from device',
  'settings.security.title': 'Security',
  'settings.security.access': 'Access',
  'settings.security.changePin': 'Change app PIN',
  'settings.security.pinDigits': '6 digits',
  'settings.security.biometrics': 'Biometric unlock',
  'settings.security.devices': 'Devices',
  'settings.security.connectedDevices': 'Connected devices',
  'settings.security.activeNetwork': 'Active network',
  'settings.security.chainNote':
      'Chain ID {chainId} · MPC transfers use BNB for network fees.',
  'settings.security.contract': 'MPC contract',
  'settings.bio.enrol':
      'Enrol a fingerprint or face in your device settings first.',
  'settings.bio.unsupported': 'This device does not support biometric unlock.',
  'settings.bio.authReason': 'Confirm to enable biometric unlock',
  'settings.bio.locked':
      'Biometrics are temporarily locked by the device. Try later.',
  'settings.bio.unavailable': 'Biometric unlock is not available right now.',
  'settings.privacy.label': 'Privacy',
  'settings.support.title': 'Help and support',
  'settings.support.getHelp': 'Get help',
  'settings.support.contact': 'Contact',
  'settings.support.contactSupport': 'Contact support',
  'settings.support.report': 'Report a problem',
  'settings.faq.recovery': 'Wallet setup & recovery',
  'settings.faq.sending': 'Sending and receiving MPC',
  'settings.faq.sendingTitle': 'Sending and receiving',
  'settings.faq.fees': 'Network fees',
  'settings.faq.security': 'Security and scams',
  'settings.recovery.title': 'Recovery phrase',
  'settings.recovery.notVerified': 'Backup not verified',
  'settings.recovery.notVerifiedBody':
      'Verify that you stored the phrase correctly.',
  'settings.recovery.controls': 'Your recovery phrase controls your wallet',
  'settings.recovery.neverShare':
      'Never share it. MPC support will never ask for it.',
  'settings.recovery.view': 'View recovery phrase',
  'settings.recovery.verify': 'Verify my backup',
  'settings.recovery.verifiedTitle': 'Backup verified',
  'settings.verify.title': 'Verify backup',
  'settings.verify.body': 'Confirm three words from your recovery phrase.',
  'settings.verify.local': 'This check stays on your device.',
  'settings.verify.word': 'Word {n}',
  'settings.verify.hint': 'Enter word {n}',
  'settings.verify.stored':
      'I stored the phrase somewhere private and offline.',
  'settings.verify.mark': 'Mark backup as verified',
  'settings.verify.wrong': 'Those words don\'t match your recovery phrase.',
  'settings.verify.unavailable':
      'Backup can only be verified on the device that created or imported this wallet.',
  'settings.verified.headline': 'Wallet backup complete',
  'settings.verified.body':
      'Your recovery phrase has been confirmed. Keep your offline copy private and secure.',
  'settings.reveal.title': 'Confirm it’s you',
  'settings.reveal.subtitle': 'Enter your app PIN',
  'settings.reveal.privacyNote': 'Make sure no one can see your screen.',
  'settings.reveal.pinLabel': 'App PIN',
  'settings.reveal.cta': 'Reveal phrase',
  'settings.reveal.warning':
      'Never copy this into a message, website, or support chat.',
  'settings.reveal.stored': 'I have stored it safely',
  'settings.reveal.unavailable': 'No recovery phrase is stored on this device.',
  'settings.reveal.appBarTitle': 'Reveal recovery phrase',
  'settings.reveal.attentionTitle': 'Attention',
  'settings.reveal.attentionBody':
      'Please read the following carefully before viewing the recovery phrase.',
  'settings.reveal.fullAccessTitle': 'Full access',
  'settings.reveal.fullAccessBody':
      'This recovery phrase gives full access to your wallet.',
  'settings.reveal.keepToYourselfTitle': 'Keep it to yourself',
  'settings.reveal.keepToYourselfBody':
      'Never send this phrase to anyone, not even to support.',
  'settings.reveal.storedSecurelyTitle': 'Stored securely',
  'settings.reveal.storedSecurelyBody':
      'Never type it into a website, a form or a message.',
  'settings.reveal.continueWithPin': 'Continue with PIN',
  'settings.reveal.pinTitle': 'Enter your 6-digit app PIN',
  'settings.reveal.pinHelper': 'Enter your app PIN',
  'settings.reveal.verifyPin': 'Verify PIN',
  'settings.reveal.phraseBody':
      'Write these words down in order and store them offline.',
  'settings.reveal.noScreenshot': 'Do not take a screenshot.',
  'settings.reveal.writtenDown': 'I wrote it down',
  'settings.about.title': 'About Global MPC',
  'settings.about.tagline': 'Mobile DApp with an embedded MPC wallet',
  'settings.about.version': 'Version {v}',
  'settings.about.terms': 'Terms of use',
  'settings.about.privacy': 'Privacy policy',
  'settings.about.licences': 'Open-source licences',
  'settings.about.website': 'Website',
  'settings.legal.title': 'Privacy and notices',
  'settings.legal.identity': 'Wallet identity',
  'settings.legal.identityValue': 'Public address only',
  'settings.legal.openSource': 'Open source',
  'settings.legal.review': 'Review',
  'settings.legal.ack': 'Third-party acknowledgements',
  'settings.pin.current': 'Current PIN',
  'settings.pin.new': 'New PIN',
  'settings.pin.confirmLabel': 'Confirm new PIN',
  'settings.pin.intro':
      'Confirm your current PIN, then choose a new 6-digit PIN.',
  'settings.pin.updateCta': 'Update PIN',
  'settings.pin.updating': 'Updating…',
  'settings.pin.updated': 'App PIN updated',
  'settings.pin.mismatch': 'PINs do not match. Try again.',
  'notif.title': 'Notifications',
  'notif.markAllRead': 'Mark all read',
  'notif.filter.all': 'All',
  'notif.filter.projects': 'Projects',
  'notif.filter.security': 'Security',
  'notif.today': 'Today',
  'notif.yesterday': 'Yesterday',
  'notif.empty.title': 'You’re all caught up',
  'notif.empty.body': 'Project, token and security updates will appear here.',
  'notif.daysAgo': '{count} days ago',
  'notif.filterEmpty': 'Nothing here yet.',
  'notif.tx.received.title': 'MPC received',
  'notif.tx.received.body': 'You received {amount} MPC.',
  'notif.tx.incoming.title': 'Incoming MPC',
  'notif.tx.incoming.body': '{amount} MPC is on its way to your wallet.',
  'notif.tx.sent.title': 'Transfer confirmed',
  'notif.tx.sent.body': 'Your transfer of {amount} MPC is confirmed.',
  'notif.tx.failed.title': 'Transfer failed',
  'notif.tx.failed.body': 'Your transfer of {amount} MPC did not go through.',
  'notif.sec.lockout.title': 'PIN entry paused',
  'notif.sec.lockout.body': 'Too many incorrect PIN attempts on this device.',
  'notif.sec.pinChanged.title': 'App PIN changed',
  'notif.sec.pinChanged.body': 'The app PIN on this device was changed.',
  'notif.sec.phraseViewed.title': 'Recovery phrase viewed',
  'notif.sec.phraseViewed.body':
      'Your recovery phrase was shown on this device.',
  'notif.sec.biometricsOn.title': 'Biometric unlock on',
  'notif.sec.biometricsOn.body':
      'Biometric unlock was turned on for this wallet.',
  'notif.sec.biometricsOff.title': 'Biometric unlock off',
  'notif.sec.biometricsOff.body':
      'Biometric unlock was turned off for this wallet.',
};
