import 'ko_screens.dart';

final Map<String, String> koStrings = {
  'app.category': '광산 RWA 비수탁형 지갑',
  'app.tagline': '실물 광산 자산을 온체인에서 검증 가능하게. 지갑과 키는 사용자 소유입니다.',
  'app.trust': '정직함 그 자체가 신뢰 자본입니다.',

  'nav.home': '홈',
  'nav.projects': '프로젝트',
  'nav.earn': '수익',
  'nav.wallet': '지갑',
  'stage.inDiscussion': '논의 중',
  'stage.secured': '확보됨',
  'stage.toBeSecured': '확보 예정',
  'stage.comingSoon': '출시 예정',
  'status.secured': '확보됨',
  'status.inProgress': '진행 중',
  'status.inDiscussion': '논의 중',
  'status.planned': '예정',
  'status.atIssuance': '발행 시 위탁',
  'status.toBeCommissioned': '위탁 예정',
  'status.designStage': '설계 단계',
  'status.afterOperations': '운영 개시 후 위탁',
  'status.provisional': '잠정 선정',
  'geo.mongolia': '몽골',
  'commodity.silicon': '규소',
  'commodity.lithium': '리튬',
  'commodity.rareEarth': '희토류',
  'commodity.tba': '추후 공개',
  'proj.tsagaan.name': '차간 톨고이 전략 광물',
  'proj.tsagaan.summary': 'MPC 파이프라인의 첫 기준 자산입니다. 개발·생산·공급 주도권은 논의 중입니다.',
  'proj.tsagaan.desc':
      'MPC 발행 표준의 첫 기준 사례입니다. 개발·생산·공급 주도권은 논의 중이며, 온체인 발행에 앞서 오프테이크 구조화와 독립 운영 감사를 위탁할 예정입니다. 자원량과 품위는 독립 Competent Person 서명 보고서로 확인되기 전까지 공개하지 않습니다.',
  'proj.additional.name': '추가 전략 자원',
  'proj.additional.summary': '논의 중입니다. 세부 내용은 추후 공개됩니다.',
  'proj.additional.desc':
      '추가 전략 자원을 논의 중입니다. 자산이 진행됨에 따라 동일한 반복 가능·감사 가능한 발행 표준에 따라 구조화 및 검증 세부사항을 공개할 예정입니다.',

  'facts.tagline': '광산 자원을 글로벌 자본시장의 언어로 번역합니다.',
  'facts.disclosure': '분기별 운영 보고와 온체인 공시.',
  'facts.plannedStandard': 'ERC-3643 · 예정',
  'scope.offChain': '오프체인',
  'scope.onChain': '온체인',
  'layer.resource.title': '자원 계층',
  'layer.resource.detail': '탐사, 실사, 오프테이크 구조화, 운영 파트너십.',
  'layer.resource.brief': '탐사, 실사',
  'layer.structuring.title': '구조화 계층',
  'layer.structuring.detail': '현금흐름 모델링, 위험 워터폴, 현지 컴플라이언스.',
  'layer.structuring.brief': '현금흐름 및 컴플라이언스 설계',
  'layer.tokenization.title': '토큰화 계층',
  'layer.tokenization.detail': 'RWA 발행, 레지스트리, 오라클 보고.',
  'layer.capital.title': '자본시장 계층',
  'layer.capital.detail': '수탁, OTC·거래소 거래, 2차 유동성.',
  'risk.resource.title': '자원 위험',
  'layer.tokenization.brief': '발행, 레지스트리, 오라클',
  'layer.capital.brief': '상장 및 2차 유동성',
  'risk.resource.detail': '독립 매장량 평가(예정).',
  'risk.operational.title': '운영 위험',
  'risk.operational.detail': 'SLA 기반 운영 통제 (설계 단계).',
  'risk.market.title': '시장 위험',
  'risk.market.detail': '원자재 헤지 메커니즘 (예정).',
  'risk.regulatory.title': '규제 위험',
  'risk.regulatory.detail': 'KYC / AML 기준 사전 적용 (예정).',
  'partner.audit': '운영 감사',
  'partner.audit.detail': '거래별로 위탁',
  'partner.tokenization': '토큰화 (ERC-3643)',
  'partner.tokenization.detail': '발행 인프라',
  'partner.oracle': '오라클 보고',
  'partner.oracle.detail': '운영 데이터 공개',
  'verify.jorc': 'JORC 실물 검증',
  'verify.cctv': 'CCTV + AI 디지털 검증',
  'verify.cp': '독립 Competent Person 보고서 (JORC / NI 43-101)',
  'tx.receive': '수신',
  'tx.send': '전송',
  'tx.allocation': '프로젝트 배정',
  'tx.issuance': '발행',
  'tx.from': '에서',
  'tx.to': '으로',
  'tx.status.completed': '완료됨',
  'tx.status.failed': '실패',
  'wallet.tx.vault': '차간 톨고이 볼트',

  'common.retry': '다시 시도',
  'common.viewAll': '전체 보기',
  'common.pending': '예정',
  'common.comingSoon': '출시 예정',

  'onboard.enter': '시작하기',
  'onboard.b1.title': '실물 광산 자산',
  'onboard.b1.body': '토큰화된 광산 프로젝트와 발행 진행 상황을 확인하세요.',
  'onboard.b2.title': '설계부터 검증 가능',
  'onboard.b2.body': '실물 검증과 온체인 공시를 함께 제공합니다.',
  'onboard.b3.title': '내 MPC 추적',
  'onboard.b3.body': '잔액과 내역, 모든 항목의 근거까지 확인하세요. 계획 총 발행량 100억.',

  'dash.balance': '추정 총액 (MPC)',
  'dash.addFunds': '입금',
  'dash.demo': '데모',
  'dash.testnet': '테스트넷',
  'dash.utilityToken': '유틸리티 토큰',
  'dash.totalSupply': '계획 발행량',
  'dash.network': '네트워크',
  'dash.listing': '상장',
  'dash.issuer': '발행사',
  'dash.contract': '컨트랙트',
  'onboard.badge': '비수탁형 지갑',
  'onboard.headline': '내 지갑은 내가 소유하고,\n증명으로 검증하세요.',
  'onboard.subhead': '하나의 안전하고 투명한 앱에서 MPC 프로젝트와 자산을 관리하세요.',
  'onboard.create': '지갑 만들기',
  'onboard.import': '지갑 가져오기',
  'dash.addressLoading': '지갑 불러오는 중…',
  'dash.addressUnavailable': '지갑을 불러올 수 없음',
  'dash.explorer': '익스플로러',
  'tour.balance.title': '내 잔액',
  'tour.balance.body': '여기에서 MPC를 확인하세요. 눈 아이콘을 눌러 금액을 숨길 수 있습니다.',
  'tour.actions.title': '빠른 실행',
  'tour.actions.body': '프로젝트, 수익, 지갑, 익스플로러로 바로 이동합니다.',
  'tour.projects.title': '광산 프로젝트',
  'tour.projects.body': '토큰화된 광산 자산과 상태를 살펴보세요.',
  'tour.settings.title': '언어 및 설정',
  'tour.settings.body': '톱니바퀴를 눌러 설정을 열면 앱 언어, 테마, 프로필을 변경할 수 있습니다.',
  'dash.projects': '광산 프로젝트',
  'dash.howItWorks': 'MPC 작동 방식',

  'proj.title': '광산 프로젝트',
  'proj.subtitle': '토큰화된 광산 프로젝트와 발행 진행 상황을 살펴보세요.',
  'proj.none': '아직 프로젝트가 없습니다',
  'proj.noneBody': '발행 진행 상황이 공개되면 프로젝트를 둘러보실 수 있습니다.',
  'proj.loadError': '프로젝트를 불러올 수 없습니다',
  'proj.loadErrorBody': '프로젝트 정보를 일시적으로 사용할 수 없습니다. 지갑에는 영향이 없습니다.',
  'proj.loadingTitle': '프로젝트를 불러오는 중',
  'proj.loadingBody': '최신 프로젝트 및 발행 정보를 확인하는 중…',
  'proj.tryAgain': '다시 시도',
  'proj.unavailable': '프로젝트를 사용할 수 없습니다',
  'proj.readiness': '발행 준비도',
  'proj.pipeline': '파이프라인',
  'proj.allocated': 'MPC 배정됨',
  'proj.productionTrend': '예상 생산 추이',
  'proj.verification': '검증',
  'proj.governance': '거버넌스 및 리스크',
  'proj.partners': '검증 네트워크',
  'proj.orchestrationNote':
      'MPC는 이들 기관을 고용하지 않고 거래별로 위탁합니다. 상태는 현재 진행 단계를 나타냅니다.',
  'proj.contract': '컨트랙트',
  'proj.tokenStandard': '발행 표준 (예정)',
  'proj.overall': '전체',
  'proj.allocatedSupply': '배정 발행량',
  'proj.hold': '이 자산 보유하기',
  'proj.notOpen': '아직 오픈되지 않음',
  'proj.viewExplorer': '블록 익스플로러에서 보기',
  'proj.notFound': '프로젝트를 찾을 수 없습니다',
  'proj.betaHold': '보유 기능은 아직 이 베타에 포함되지 않았습니다.',

  ...koScreensStrings,
};
