// GENERATED-STRUCTURE, HAND-TRANSLATED CONTENT.
// Korean (한국어) translations for the MPC app.
// Production-usable. Reviewed for the Korean market.
// Keys must stay in sync with en.dart (the source of truth).

const Map<String, String> koStrings = {
  'app.category': '광산 RWA 인프라',
  'app.tagline': '실물 광산 자산을 온체인에서 투자 가능하게. 몽골에서 시작합니다.',
  'app.trust': '정직함 그 자체가 신뢰 자본입니다.',

  'nav.home': '홈',
  'nav.projects': '프로젝트',
  'nav.earn': '수익',
  'nav.wallet': '지갑',
  'stage.inDiscussion': '논의 중',
  'stage.secured': '확보됨',
  'stage.toBeSecured': '확보 예정',
  'stage.comingSoon': '출시 예정',
  'status.secured': '확보됨',
  'status.inProgress': '진행 중',
  'status.inDiscussion': '논의 중',
  'status.planned': '예정',
  'status.atIssuance': '발행 시 위탁',
  'status.toBeCommissioned': '위탁 예정',
  'status.designStage': '설계 단계',
  'status.afterOperations': '운영 개시 후 위탁',
  'status.provisional': '잠정 선정',
  'geo.mongolia': '몽골',
  'commodity.silicon': '규소',
  'commodity.lithium': '리튬',
  'commodity.rareEarth': '희토류',
  'commodity.tba': '추후 공개',
  'proj.tsagaan.name': '차간 톨고이 전략 광물',
  'proj.tsagaan.summary': 'MPC 파이프라인의 첫 기준 자산입니다. 개발·생산·공급 주도권은 논의 중입니다.',
  'proj.tsagaan.desc':
      'MPC 발행 표준의 첫 기준 사례입니다. 개발·생산·공급 주도권은 논의 중이며, 온체인 발행에 앞서 오프테이크 구조화와 독립 운영 감사를 위탁할 예정입니다. 자원량과 품위는 독립 Competent Person 서명 보고서로 확인되기 전까지 공개하지 않습니다.',
  'proj.additional.name': '추가 전략 자원',
  'proj.additional.summary': '논의 중입니다. 세부 내용은 추후 공개됩니다.',
  'proj.additional.desc':
      '추가 전략 자원을 논의 중입니다. 자산이 진행됨에 따라 동일한 반복 가능·감사 가능한 발행 표준에 따라 구조화 및 검증 세부사항을 공개할 예정입니다.',

  'facts.tagline': '몽골의 광산 자원을 글로벌 자본시장의 언어로 번역합니다.',
  'facts.disclosure': '분기별 운영 보고와 온체인 공시.',
  'facts.plannedStandard': 'ERC-3643 · 예정',
  'scope.offChain': '오프체인',
  'scope.onChain': '온체인',
  'layer.resource.title': '자원 계층',
  'layer.resource.detail': '탐사, 실사, 오프테이크 구조화, 운영 파트너십.',
  'layer.structuring.title': '구조화 계층',
  'layer.structuring.detail': '현금흐름 모델링, 위험 워터폴, 현지 컴플라이언스.',
  'layer.tokenization.title': '토큰화 계층',
  'layer.tokenization.detail': 'RWA 발행, 레지스트리, 오라클 보고.',
  'layer.capital.title': '자본시장 계층',
  'layer.capital.detail': '수탁, OTC·거래소 거래, 2차 유동성.',
  'risk.resource.title': '자원 위험',
  'risk.resource.detail': '독립 매장량 평가(예정).',
  'risk.operational.title': '운영 위험',
  'risk.operational.detail': 'SLA 기반 운영 통제 (설계 단계).',
  'risk.market.title': '시장 위험',
  'risk.market.detail': '원자재 헤지 메커니즘 (예정).',
  'risk.regulatory.title': '규제 위험',
  'risk.regulatory.detail': 'KYC / AML 기준 사전 적용 (예정).',
  'partner.audit': '운영 감사',
  'partner.tokenization': '토큰화 (ERC-3643)',
  'partner.oracle': '오라클 보고',
  'verify.jorc': 'JORC 실물 검증',
  'verify.cctv': 'CCTV + AI 디지털 검증',
  'verify.cp': '독립 Competent Person 보고서 (JORC / NI 43-101)',
  'tx.receive': '수신',
  'tx.send': '전송',
  'tx.allocation': '프로젝트 배정',
  'tx.issuance': '발행',
  'wallet.tx.vault': '차간 톨고이 볼트',

  'common.retry': '다시 시도',
  'common.viewAll': '전체 보기',
  'common.pending': '예정',
  'common.comingSoon': '출시 예정',

  'onboard.enter': '시작하기',
  'onboard.b1.title': '실물 광산 자산',
  'onboard.b1.body': '몽골 광산 프로젝트와 발행 진행 상황을 확인하세요.',
  'onboard.b2.title': '설계부터 검증 가능',
  'onboard.b2.body': '실물 검증과 온체인 공시를 함께 제공합니다.',
  'onboard.b3.title': '내 MPC 추적',
  'onboard.b3.body': '잔액과 내역, 모든 항목의 근거까지 확인하세요. 총 발행량 100억.',

  'dash.balance': '추정 총액 (MPC)',
  'dash.addFunds': '입금',
  'dash.demo': '데모',
  'dash.testnet': '테스트넷',
  'dash.utilityToken': '유틸리티 토큰',
  'dash.totalSupply': '총 발행량',
  'dash.network': '네트워크',
  'dash.listing': '상장',
  'dash.issuer': '발행사',
  'dash.contract': '컨트랙트',
  'dash.explorer': '익스플로러',
  'tour.balance.title': '내 잔액',
  'tour.balance.body': '여기에서 MPC를 확인하세요. 눈 아이콘을 눌러 금액을 숨길 수 있습니다.',
  'tour.actions.title': '빠른 실행',
  'tour.actions.body': '프로젝트, 수익, 지갑, 익스플로러로 바로 이동합니다.',
  'tour.projects.title': '광산 프로젝트',
  'tour.projects.body': '토큰화된 몽골 광산 자산과 상태를 살펴보세요.',
  'tour.settings.title': '언어 및 설정',
  'tour.settings.body': '톱니바퀴를 눌러 설정을 열면 앱 언어, 테마, 프로필을 변경할 수 있습니다.',
  'dash.projects': '광산 프로젝트',
  'dash.howItWorks': 'MPC 작동 방식',

  'proj.title': '광산 프로젝트',
  'proj.none': '아직 프로젝트가 없습니다',
  'proj.loadError': '프로젝트를 불러올 수 없습니다',
  'proj.unavailable': '프로젝트를 사용할 수 없습니다',
  'proj.readiness': '발행 준비도',
  'proj.pipeline': '파이프라인',
  'proj.allocated': 'MPC 배정됨',
  'proj.productionTrend': '예상 생산 추이',
  'proj.verification': '검증',
  'proj.governance': '거버넌스 및 리스크',
  'proj.partners': '검증 네트워크',
  'proj.orchestrationNote':
      'MPC는 이들 기관을 고용하지 않고 거래별로 위탁합니다. 상태는 현재 진행 단계를 나타냅니다.',
  'proj.contract': '컨트랙트',
  'proj.tokenStandard': '발행 표준 (예정)',
  'proj.overall': '전체',
  'proj.allocatedSupply': '배정 발행량',
  'proj.hold': '이 자산 보유하기',
  'proj.notOpen': '아직 오픈되지 않음',
  'proj.viewExplorer': '블록 익스플로러에서 보기',
  'proj.notFound': '프로젝트를 찾을 수 없습니다',
  'proj.betaHold': '보유 기능은 아직 이 베타에 포함되지 않았습니다.',

  'wallet.title': '지갑',
  'wallet.totalBalance': '총 잔액',
  'wallet.demoNotice': '데모 지갑입니다. 이 베타에서는 실제 키가 생성되거나 저장되지 않습니다.',
  'wallet.allocations': '배정 내역',
  'wallet.activity': '활동 내역',
  'wallet.receive': '받기',
  'wallet.send': '보내기',
  'wallet.unallocated': '미배정',
  'wallet.noAllocations': '아직 배정 내역이 없습니다',
  'wallet.noAllocationsBody': '진행 중인 광산 프로젝트에 MPC를 보유하면 여기에 표시됩니다.',
  'wallet.unavailable': '지갑을 사용할 수 없습니다',
  'wallet.addressCopied': '주소가 복사되었습니다',
  'wallet.transfersLater': '전송 기능은 이후 단계에서 제공됩니다.',

  'earn.title': '수익',
  'earn.gatedBanner':
      '수익 기능은 아직 제공되지 않습니다. 스테이킹과 파밍은 상장과 신원 인증(KYC) 이후에만 열립니다. 현재 표시할 수 있는 수익률은 없습니다.',
  'earn.status.planned': '예정',
  'earn.rateLabel': '보상률',
  'earn.ratePending': '상장 시 공지',
  'earn.notify': '알림 받기',
  'earn.notifyToast': '수익 기능이 열리면 알려드리겠습니다.',
  'earn.staking.title': '스테이킹',
  'earn.staking.body':
      'MPC를 예치하여 광산 자산 발행을 지원합니다. 보상 조건은 상장 시 프로그램이 열릴 때 공개됩니다.',
  'earn.farming.title': '파밍',
  'earn.farming.body':
      '토큰 상장 후 MPC 유동성을 공급하고 거래 활동으로부터 수익을 얻습니다. 조건은 상장 시 공개됩니다.',
  'earn.whyGated': '왜 아직인가요?',
  'earn.gate.kyc.title': '신원 인증 (KYC)',
  'earn.gate.kyc.body':
      'MPC 발행은 허가형 표준인 ERC-3643 기반으로 설계되어, 수익 활동에는 인증된 신원이 필요합니다.',
  'earn.gate.listing.title': '상장',
  'earn.gate.listing.body': '보상률과 풀은 MPC 상장 시 결정됩니다. 그 전에는 어떤 수치도 표시하지 않습니다.',

  'settings.title': '설정',
  'settings.profile': '프로필',
  'settings.language': '언어',
  'settings.appearance': '테마',
  'theme.system': '시스템 설정',
  'theme.light': '라이트',
  'theme.dark': '다크',
  'profile.title': '프로필',
  'profile.details': '계정 정보',
  'profile.walletAddress': '주소',
};
