const Map<String, String> koScreensStrings = {
  'wallet.title': '지갑',
  'wallet.totalBalance': '총 잔액',
  'wallet.demoNotice': '데모 지갑입니다. 이 베타에서는 실제 키가 생성되거나 저장되지 않습니다.',
  'wallet.allocations': '배정 내역',
  'wallet.activity': '활동 내역',
  'wallet.receive': '받기',
  'wallet.send': '보내기',
  'wallet.unallocated': '미배정',
  'wallet.noAllocations': '아직 배정 내역이 없습니다',
  'wallet.noAllocationsBody': '진행 중인 프로젝트에 MPC를 보유하면 여기에 표시됩니다.',
  'wallet.noTransactions': '아직 거래 내역이 없습니다',
  'wallet.noTransactionsBody': '거래 내역이 여기에 표시됩니다.',
  'wallet.loading.title': '지갑 불러오는 중',
  'wallet.loading.body': '잔액과 최근 활동을 확인하는 중…',
  'wallet.tryAgain': '다시 시도',
  'wallet.unavailable': '지갑을 사용할 수 없습니다',
  'wallet.unavailableBody': '잔액을 불러오지 못했습니다. 지갑은 안전하게 보호되고 있습니다.',
  'wallet.addressCopied': '주소가 복사되었습니다',
  'wallet.transfersLater': '전송 기능은 이후 단계에서 제공됩니다.',

  'earn.title': '수익',
  'earn.gatedBanner': '수익 기능은 계획 단계이며, 상장 및 자격 요건이 확인될 때까지 제한됩니다.',
  'earn.status.planned': '예정',
  'earn.rateLabel': '보상률',
  'earn.ratePending': '상장 시 공지',
  'earn.notify': '알림 받기',
  'earn.notifyToast': '이 기능이 열리면 알려드리겠습니다.',
  'earn.staking.title': '스테이킹',
  'earn.staking.body':
      'MPC를 예치하여 광산 자산 발행을 지원합니다. 보상 조건은 상장 시 프로그램이 열릴 때 공개됩니다.',
  'earn.farming.title': '파밍',
  'earn.farming.body':
      '토큰 상장 후 MPC 유동성을 공급하고 거래 활동으로부터 수익을 얻습니다. 조건은 상장 시 공개됩니다.',
  'earn.whyGated': '왜 아직인가요?',
  'earn.gate.kyc.title': '신원 인증 (KYC)',
  'earn.gate.kyc.body': 'MPC 발행은 ERC-3643 기반으로 설계되어, 수익 활동에는 인증된 신원이 필요합니다.',
  'earn.gate.listing.title': '상장',
  'earn.gate.listing.body': '보상률과 풀은 MPC 상장 시 결정됩니다.',

  'settings.title': '설정',
  'settings.profile': '프로필',
  'settings.language': '언어',
  'settings.appearance': '테마',
  'settings.section.preferences': '환경설정',
  'settings.section.wallet': '지갑 및 보안',
  'settings.section.appInfo': '지원 및 법적 정보',
  'settings.needHelp': '도움이 필요하신가요?',
  'settings.helpSupport': '도움말 및 지원',
  'settings.notify.label': '알림',
  'settings.notify.manage': '관리',
  'settings.notify.title': '알림',
  'settings.notify.transactions': '거래 업데이트',
  'settings.notify.transactionsBody': 'MPC 송수신 상태 변경 알림입니다.',
  'settings.notify.security': '보안 알림',
  'settings.notify.securityBody': 'PIN, 복구 및 기기 보안 관련 이벤트입니다.',
  'settings.notify.projects': '프로젝트 업데이트',
  'settings.notify.projectsBody': '팔로우한 프로젝트의 주요 상태 변경 알림입니다.',
  'settings.security': '보안',
  'settings.pinBiometrics': 'PIN 및 생체인식',
  'settings.backup': '백업 및 복구',
  'settings.verifyBackup': '백업 확인',
  'settings.about': 'MPC 소개',
  'settings.privacyNotices': '개인정보 및 오픈소스 고지',
  'settings.rateUs': '평가하기',
  'settings.review': '리뷰',
  'settings.removeWallet': '이 기기에서 지갑 삭제',
  'lang.chooseLanguage': '언어 선택',
  'lang.applyLanguage': '언어 적용',
  'lang.selected': '선택됨',

  'wallet.create.title': '지갑 만들기',
  'wallet.create.step0.header': '오직 나만의 지갑',
  'wallet.create.step0.body':
      'MPC가 이 기기에서 지갑을 생성합니다. 기기를 잃어버릴 경우, 복구 구문만이 접근을 복원하는 유일한 방법입니다.',
  'wallet.create.step0.holdKeys': '키를 직접 보관',
  'wallet.create.step0.holdKeysBody': 'MPC는 구문을 복구하거나 초기화할 수 없습니다.',
  'wallet.create.step0.backupOffline': '오프라인 백업',
  'wallet.create.step0.backupOfflineBody': '단어를 적어 두고 비공개로 보관하세요.',
  'wallet.create.step0.protectDevice': '기기 보호',
  'wallet.create.step0.protectDeviceBody': 'PIN을 설정하고 선택적으로 생체인식을 사용하세요.',
  'wallet.create.step0.button': '새 지갑 만들기',
  'wallet.create.step1.header': '복구 구문 백업',
  'wallet.create.step1.body': '이 12개의 단어를 순서대로 적으세요.',
  'wallet.create.step1.phraseLabel': '복구 구문',
  'wallet.create.step1.saved': '단어를 저장했습니다',
  'wallet.create.step1.download': '다운로드',
  'wallet.create.step1.copy': '코드 복사',
  'wallet.create.step1.warning':
      '누구에게도 이 단어를 공유하지 마세요. MPC 지원팀은 복구 구문을 절대 요청하지 않습니다.',
  'wallet.create.step1.copied': '복구 구문이 복사되었습니다. 클립보드는 30초 후 지워집니다.',
  'wallet.create.step1.saveDigital': '디지털로 저장하시겠습니까?',
  'wallet.create.step1.saveDigitalBody':
      '저장하는 앱이나 클라우드 서비스에서 복구 구문을 읽을 수 있습니다. 오프라인으로 단어를 기록하는 것이 더 안전합니다.',
  'wallet.create.step1.saveCancel': '취소',
  'wallet.create.step1.saveContinue': '계속',
  'wallet.create.step2.header': '백업 확인',
  'wallet.create.step2.body': '요청된 단어를 선택하여 백업을 확인하세요.',
  'wallet.create.step2.button': '백업 확인',
  'wallet.create.step2.mismatchTitle': '단어가 일치하지 않습니다',
  'wallet.create.step2.mismatchBody': '복구 구문을 확인하고 다시 시도하세요. 다음엔 다른 단어를 요청합니다.',
  'wallet.create.step2.wordLabel': '{n}번째 단어',
  'wallet.create.step2.wordHint': '{n}번째 단어 입력',
  'wallet.create.pin.createTitle': '앱 PIN 만들기',
  'wallet.create.pin.createBody': '이 PIN으로 이 기기에서 MPC를 잠금 해제하세요.',
  'wallet.create.pin.confirmTitle': 'PIN 확인',
  'wallet.create.pin.confirmBody': '동일한 6자리 PIN을 다시 입력하세요.',
  'wallet.create.pin.hint': 'PIN은 이 기기만 보호합니다.',
  'wallet.create.pin.safeTitle': '지갑은 여전히 안전합니다',
  'wallet.create.pin.safeBody': '저장되거나 변경된 내용이 없습니다. PIN을 다시 입력하여 계속하세요.',
  'wallet.create.pin.continue': '계속',
  'wallet.create.pin.reEnter': 'PIN 다시 입력',
  'wallet.create.pin.confirm': 'PIN 확인',
  'wallet.create.pin.mismatch': 'PIN이 일치하지 않습니다. 다시 시도하세요.',
  'wallet.create.biometric.title': '지갑 보호',
  'wallet.create.biometric.body': '생체인식 보안을 추가하면 본인만 지갑에 접근할 수 있습니다.',
  'wallet.create.biometric.faceId': 'Face ID / Touch ID',
  'wallet.create.biometric.recommended': '권장',
  'wallet.create.biometric.finish': '설정 완료',
  'wallet.create.securing.title': '지갑 생성 중',
  'wallet.create.securing.body': '새 MPC 지갑 추가 중…',
  'wallet.create.securing.keepOpen': 'MPC를 열어두세요',
  'wallet.create.securing.keepOpenBody': '보안 확인이 완료될 때까지 앱을 닫지 마세요.',
  'wallet.create.securing.inProgress': '지갑 보안 설정 중…',
  'wallet.create.done.title': '지갑이 생성되었습니다',
  'wallet.create.done.body': '지갑이 보호되어 사용 준비가 되었습니다.',
  'wallet.create.done.open': '지갑 열기',

  'wallet.import.syncing.title': '지갑 가져오는 중',
  'wallet.import.syncing.body': '이 기기를 보호하고 지갑 데이터를 동기화하는 중…',

  'wallet.secure.done.title': '지갑이 보호되었습니다',
  'wallet.secure.done.body': '지갑이 이 기기와 새 PIN으로 보호됩니다.',

  'wallet.secure.failed.title': '지갑을 보안할 수 없습니다',
  'wallet.secure.failed.body': '이 기기에 지갑 데이터가 저장되지 않았습니다.',
  'wallet.secure.failed.deviceTitle': '기기 보안을 사용할 수 없습니다',
  'wallet.secure.failed.deviceBody': '저장소 및 기기 보안 설정을 확인한 후 다시 시도하세요.',
  'wallet.secure.failed.retry': '다시 시도',
  'wallet.secure.failed.returnToWelcome': '시작 화면으로 돌아가기',

  'wallet.import.title': '지갑 가져오기',
  'wallet.import.secure': '지갑 보안',
  'wallet.import.step0.header': '기존 지갑 복원',
  'wallet.import.step0.body': '복구 구문을 입력하기 전에:',
  'wallet.import.step0.keepPrivate': '비공개 유지',
  'wallet.import.step0.keepPrivateBody': '화면을 아무도 보지 못하게 하세요.',
  'wallet.import.step0.enterOnly': '여기서만 입력',
  'wallet.import.step0.enterOnlyBody': '구문을 지원팀에 절대 보내지 마세요.',
  'wallet.import.step0.stored': '안전하게 저장',
  'wallet.import.step0.storedBody': 'MPC가 기기와 PIN으로 접근을 보호합니다.',
  'wallet.import.step0.understand': '이해했습니다',
  'wallet.import.phrase.header': '복구 구문 입력',
  'wallet.import.phrase.body': '올바른 순서로 단어를 입력하세요.',
  'wallet.import.phrase.label': '복구 구문',
  'wallet.import.phrase.hint': '복구 단어를 붙여넣거나 입력하세요',
  'wallet.import.phrase.support': 'MPC 지원팀은 복구 구문을 절대 요청하지 않습니다.',
  'wallet.import.phrase.errorEmpty': '계속하려면 복구 구문을 입력하세요.',
  'wallet.import.phrase.errorInvalid': '유효하지 않은 복구 구문입니다. 단어와 순서를 확인하세요.',
  'wallet.import.phrase.review': '지갑 확인',
  'wallet.import.address.header': '지갑 확인',
  'wallet.import.address.body': '계속하기 전에 지갑 주소를 확인하세요.',
  'wallet.import.address.label': '지갑 주소',
  'wallet.import.address.confirm': '이것이 내 지갑입니다',
  'wallet.import.ready.title': '지갑을 가져왔습니다',
  'wallet.import.ready.body': '기존 지갑이 이 기기에서 준비되었습니다.',
  'wallet.import.ready.securityComplete': '보안 완료',
  'wallet.import.ready.securityBody': '복구 구문은 다른 기기에서 접근을 복원하는 유일한 방법입니다.',
  'wallet.import.ready.open': '지갑 열기',

  'wallet.secure.failed': '지갑을 보호할 수 없었습니다',
  'wallet.secure.noData': '이 기기에 저장된 지갑 데이터가 없습니다.',
  'wallet.secure.unavailable': '기기 보안 사용 불가',
  'wallet.secure.checkSettings': '저장소 및 기기 보안 설정을 확인한 후 다시 시도하세요.',
  'wallet.secure.retry': '다시 시도',
  'wallet.secure.returnWelcome': '환영 화면으로 돌아가기',

  'wallet.phrase.words': '{count}개 단어',

  'theme.system': '시스템 설정',
  'theme.light': '라이트',
  'theme.dark': '다크',
  'theme.apply': '테마 적용',
  'profile.title': '프로필',
  'profile.details': '계정 정보',
  'profile.walletAddress': '주소',

  'unlock.welcomeBack': '다시 오셨군요',
  'unlock.enterPin': 'PIN을 입력하여 지갑을 잠금 해제하세요.',
  'unlock.forgotPin': 'PIN을 잊으셨나요? 지갑 복원',
  'unlock.unlock': '지갑 잠금 해제',
  'unlock.unlocking': '잠금 해제 중…',
  'unlock.useBiometrics': '생체인식 사용',
  'unlock.newToMpc': 'MPC가 처음이신가요? ',
  'unlock.pinPrivacy': 'PIN은 이 기기를 벗어나지 않습니다.',
  'unlock.biometricSheet.title': 'MPC 잠금 해제',
  'unlock.biometricSheet.body': 'Touch ID 또는 Face ID로 확인하세요',
  'unlock.restore.title': '지갑을 복원할까요?',
  'unlock.restore.body': '기기 PIN으로는 지갑을 복구할 수 없습니다. 복구 구문이 있는 경우에만 계속하세요.',

  'common.cancel': '취소',
  'common.done': '완료',
  'common.continueBtn': '계속',
  'common.on': '켜기',
  'common.off': '끄기',
  'common.thisDevice': '이 기기',
  'common.gotIt': '확인했습니다',
  'common.pin.incomplete': '6자리 모두 입력하세요.',
  'common.pin.incorrect': 'PIN이 올바르지 않습니다. 다시 시도하세요.',
  'common.inProgress': '진행 중',
  'receive.title': '{asset} 받기',
  'receive.unavailable': '지갑 주소를 사용할 수 없음',
  'receive.warning': '이 주소로는 {asset}과(와) 지원되는 BNB Smart Chain 자산만 보내세요.',
  'receive.copy': '주소 복사',
  'receive.share': '주소 공유',
  'receive.shareTemplate': 'BNB Smart Chain의 내 {asset} 지갑 주소:\n{address}',
  'receive.wrongNetwork': '다른 네트워크에서 보낸 자산은 영구히 손실될 수 있습니다.',
  'send.title': 'MPC 보내기',
  'send.reviewShort': '보내기',
  'send.pin.title': 'PIN으로 확인',
  'send.unavailableBody': '보내기 전에 지갑을 다시 불러오세요.',
  'send.recipient': '받는 주소',
  'send.recipientHint': '올바른 지갑 주소를 붙여넣으세요',
  'send.paste': '붙여넣기',
  'send.amount': '수량',
  'send.useMax': '최대 사용',
  'send.available': '{amount} 사용 가능',
  'send.safety': '받는 사람과 네트워크를 신중히 확인하세요. 블록체인 거래는 되돌릴 수 없습니다.',
  'send.review.cta': '거래 검토',
  'send.review.sending': '보내는 금액',
  'send.review.to': '받는 사람',
  'send.review.copyRecipient': '받는 주소 복사',
  'send.review.fee': '네트워크 수수료',
  'send.review.feeValue': '~{fee} BNB',
  'send.review.notEnoughBnb': 'BNB가 부족합니다',
  'send.review.note': '제출 후에는 이 거래를 변경하거나 취소할 수 없습니다.',
  'send.review.confirm': '확인하고 계속',
  'send.review.edit': '거래 편집',
  'send.amountMpc': '{amount} MPC',
  'send.gas.title': '네트워크 수수료에 BNB가 필요합니다',
  'send.gas.body': '이 전송에는 약 {fee} BNB가 필요합니다. 지갑에는 {bnb} BNB가 있습니다.',
  'send.gas.needed': '필요량',
  'send.gas.note': '이 수수료에는 MPC 잔액이 사용되지 않습니다.',
  'send.gas.receive': 'BNB 받기',
  'send.gasInfo.title': '예상 네트워크 수수료',
  'send.gasInfo.body': '이것은 BNB 스마트 체인 전송 가스비입니다.',
  'send.pin.prompt': '6자리 앱 PIN을 입력하세요',
  'send.pin.confirm': '이 작업은 {amount} MPC를 보내는 사람이 본인임을 확인합니다.',
  'send.pin.hint': '앱 PIN 입력',
  'send.processing.title': '거래 처리 중',
  'send.processing.body': '완료될 때까지 MPC를 열어 두세요.',
  'send.success.title': '거래 제출됨',
  'send.success.headline': 'MPC 전송됨',
  'send.success.body': '{amount} MPC가 {address}에 제출되었습니다.',
  'send.success.status': '상태',
  'send.success.pending': '확인 대기 중',
  'send.success.view': '거래 보기',
  'send.success.back': '지갑으로 돌아가기',
  'send.failure.title': '거래가 전송되지 않음',
  'send.failure.body': '잔액은 변경되지 않았습니다. 연결을 확인하고 다시 시도하세요.',
  'send.failure.retry': '다시 시도',
  'send.failure.cancel': '전송 취소',
  'send.error.address': '올바른 BNB Smart Chain 주소를 입력하세요.',
  'send.error.self': '본인의 지갑 주소입니다.',
  'send.error.zero': '0보다 큰 금액을 입력하세요.',
  'send.error.balance': '미할당 MPC는 {amount}뿐입니다.',
  'tx.details.title': '거래 상세',
  'tx.details.status': '상태',
  'tx.details.from': '보낸 사람',
  'tx.details.to': '받는 사람',
  'tx.details.vault': '프로젝트 볼트',
  'tx.details.date': '날짜',
  'tx.details.hash': '거래 해시',
  'tx.status.submitted': '제출됨',
  'tx.status.pending': '대기 중',
  'tx.status.confirmed': '확인됨',

  'settings.remove.title': '지갑을 삭제할까요?',
  'settings.remove.body':
      '이 기기에서 지갑 접근 권한과 PIN이 삭제됩니다. 지갑을 복구하려면 복구 구문이 필요합니다.',
  'settings.remove.type': '계속하려면 REMOVE를 입력하세요.',
  'settings.remove.keep': '지갑 유지',
  'settings.remove.confirm': '기기에서 제거',
  'settings.security.title': '보안',
  'settings.security.access': '접근',
  'settings.security.changePin': '앱 PIN 변경',
  'settings.security.pinDigits': '6자리',
  'settings.security.biometrics': '생체인식 잠금 해제',
  'settings.security.devices': '기기',
  'settings.security.connectedDevices': '연결된 기기',
  'settings.security.activeNetwork': '활성 네트워크',
  'settings.security.chainNote': '체인 ID {chainId} · MPC 전송은 수수료로 BNB를 사용합니다.',
  'settings.security.contract': 'MPC 컨트랙트',
  'settings.bio.enrol': '먼저 기기 설정에서 지문 또는 얼굴을 등록하세요.',
  'settings.bio.unsupported': '이 기기는 생체인식 잠금 해제를 지원하지 않습니다.',
  'settings.bio.authReason': '생체인식 잠금 해제를 활성화하려면 확인하세요',
  'settings.bio.locked': '기기에서 생체인식을 일시적으로 잠갔습니다. 나중에 다시 시도하세요.',
  'settings.bio.unavailable': '지금은 생체인식 잠금 해제를 사용할 수 없습니다.',
  'settings.privacy.label': '개인정보',
  'settings.support.title': '도움말 및 지원',
  'settings.support.getHelp': '도움 받기',
  'settings.support.contact': '문의',
  'settings.support.contactSupport': '고객 지원 문의',
  'settings.support.report': '문제 신고',
  'settings.faq.recovery': '지갑 설정 및 복구',
  'settings.faq.sending': 'MPC 보내기 및 받기',
  'settings.faq.sendingTitle': '보내기 및 받기',
  'settings.faq.fees': '네트워크 수수료',
  'settings.faq.security': '보안 및 사기',
  'settings.recovery.title': '복구 구문',
  'settings.recovery.notVerified': '백업 미확인',
  'settings.recovery.notVerifiedBody': '구문을 올바르게 보관했는지 확인하세요.',
  'settings.recovery.controls': '복구 구문이 지갑을 관리합니다',
  'settings.recovery.neverShare': '절대 공유하지 마세요. MPC 지원팀은 이를 요청하지 않습니다.',
  'settings.recovery.view': '복구 구문 보기',
  'settings.recovery.verify': '백업 확인',
  'settings.recovery.verifiedTitle': '백업 확인됨',
  'settings.verify.title': '백업 확인',
  'settings.verify.body': '복구 구문의 단어 세 개를 확인하세요.',
  'settings.verify.local': '이 확인은 기기 내에서만 이루어집니다.',
  'settings.verify.word': '{n}번째 단어',
  'settings.verify.hint': '{n}번째 단어 입력',
  'settings.verify.stored': '구문을 안전하고 오프라인으로 보관했습니다.',
  'settings.verify.mark': '백업을 확인됨으로 표시',
  'settings.verify.wrong': '단어가 복구 구문과 일치하지 않습니다.',
  'settings.verify.unavailable': '백업은 이 지갑을 만들거나 가져온 기기에서만 확인할 수 있습니다.',
  'settings.verified.headline': '지갑 백업 완료',
  'settings.verified.body': '복구 구문이 확인되었습니다. 오프라인 사본을 안전하게 보관하세요.',
  'settings.reveal.title': '본인 확인',
  'settings.reveal.subtitle': '앱 PIN 입력',
  'settings.reveal.privacyNote': '다른 사람이 화면을 보지 못하는지 확인하세요.',
  'settings.reveal.pinLabel': '앱 PIN',
  'settings.reveal.cta': '구문 표시',
  'settings.reveal.warning': '이 내용을 메시지, 웹사이트, 고객 지원 채팅에 복사하지 마세요.',
  'settings.reveal.stored': '안전하게 보관했습니다',
  'settings.reveal.unavailable': '이 기기에 저장된 복구 구문이 없습니다.',
  'settings.reveal.appBarTitle': '복구 구문 보기',
  'settings.reveal.attentionTitle': '주의',
  'settings.reveal.attentionBody': '복구 구문을 보기 전에 아래 내용을 주의 깊게 읽어주세요.',
  'settings.reveal.fullAccessTitle': '전체 접근 권한',
  'settings.reveal.fullAccessBody': '이 복구 구문은 지갑에 대한 전체 접근 권한을 부여합니다.',
  'settings.reveal.keepToYourselfTitle': '본인만 알고 있어야 합니다',
  'settings.reveal.keepToYourselfBody': '이 구문은 고객지원팀을 포함해 누구에게도 보내지 마세요.',
  'settings.reveal.storedSecurelyTitle': '안전하게 보관',
  'settings.reveal.storedSecurelyBody': '웹사이트, 입력 양식, 메시지에 절대 입력하지 마세요.',
  'settings.reveal.continueWithPin': 'PIN으로 계속하기',
  'settings.reveal.pinTitle': '6자리 앱 PIN을 입력하세요',
  'settings.reveal.pinHelper': '앱 PIN 입력',
  'settings.reveal.verifyPin': 'PIN 확인',
  'settings.reveal.phraseBody': '이 단어들을 순서대로 적어 오프라인에 보관하세요.',
  'settings.reveal.noScreenshot': '스크린샷을 찍지 마세요.',
  'settings.reveal.writtenDown': '적어두었습니다',
  'wallet.import.biometric.finish': '가져오기 완료',
  'settings.about.title': 'Global MPC 정보',
  'settings.about.tagline': 'MPC 광산 토큰화 생태계를 위한 비수탁형 지갑',
  'settings.about.version': '버전 {v}',
  'settings.about.terms': '이용약관',
  'settings.about.privacy': '개인정보 처리방침',
  'settings.about.licences': '오픈소스 라이선스',
  'settings.about.website': '웹사이트',
  'settings.legal.title': '개인정보 및 고지',
  'settings.legal.identity': '지갑 신원',
  'settings.legal.identityValue': '공개 주소만',
  'settings.legal.openSource': '오픈소스',
  'settings.legal.review': '보기',
  'settings.legal.ack': '서드파티 고지',
  'settings.pin.current': '현재 PIN',
  'settings.pin.new': '새 PIN',
  'settings.pin.confirmLabel': '새 PIN 확인',
  'settings.pin.intro': '현재 PIN을 확인한 후 새 6자리 PIN을 선택하세요.',
  'settings.pin.updateCta': 'PIN 업데이트',
  'settings.pin.updating': '업데이트 중…',
  'settings.pin.updated': '앱 PIN이 업데이트되었습니다',
  'settings.pin.mismatch': 'PIN이 일치하지 않습니다. 다시 시도하세요.',
  'notif.title': '알림',
  'notif.markAllRead': '모두 읽음',
  'notif.filter.all': '전체',
  'notif.filter.projects': '프로젝트',
  'notif.filter.security': '보안',
  'notif.today': '오늘',
  'notif.yesterday': '어제',
  'notif.empty.title': '모두 확인했습니다',
  'notif.empty.body': '프로젝트, 토큰, 보안 업데이트가 여기에 표시됩니다.',
  'notif.daysAgo': '{count}일 전',
  'notif.filterEmpty': '아직 표시할 알림이 없습니다.',
  'notif.tx.received.title': 'MPC 수신됨',
  'notif.tx.received.body': '{amount} MPC를 받았습니다.',
  'notif.tx.incoming.title': 'MPC 입금 중',
  'notif.tx.incoming.body': '{amount} MPC가 지갑으로 전송 중입니다.',
  'notif.tx.sent.title': '전송 완료',
  'notif.tx.sent.body': '{amount} MPC 전송이 확인되었습니다.',
  'notif.tx.failed.title': '전송 실패',
  'notif.tx.failed.body': '{amount} MPC 전송이 완료되지 않았습니다.',
  'notif.sec.lockout.title': 'PIN 입력 일시 중지',
  'notif.sec.lockout.body': '이 기기에서 잘못된 PIN 입력이 너무 많습니다.',
  'notif.sec.pinChanged.title': '앱 PIN 변경됨',
  'notif.sec.pinChanged.body': '이 기기의 앱 PIN이 변경되었습니다.',
  'notif.sec.phraseViewed.title': '복구 구문 조회됨',
  'notif.sec.phraseViewed.body': '이 기기에서 복구 구문이 표시되었습니다.',
  'notif.sec.biometricsOn.title': '생체 인증 잠금 해제 켜짐',
  'notif.sec.biometricsOn.body': '이 지갑의 생체 인증 잠금 해제가 켜졌습니다.',
  'notif.sec.biometricsOff.title': '생체 인증 잠금 해제 꺼짐',
  'notif.sec.biometricsOff.body': '이 지갑의 생체 인증 잠금 해제가 꺼졌습니다.',
};
