import 'mn_screens.dart';

final Map<String, String> mnStrings = {
  'app.category': 'Уул уурхайн RWA-ийн хадгаламжгүй хэтэвч',
  'app.tagline':
      'Бодит уул уурхайн хөрөнгийг ончейн шалгах боломжтой болгоно. Хэтэвч ба түлхүүр таны өмч.',
  'app.trust': 'Шударга байдал өөрөө итгэлцлийн капитал юм.',

  'nav.home': 'Нүүр',
  'nav.projects': 'Төслүүд',
  'nav.earn': 'Орлого',
  'nav.wallet': 'Хэтэвч',
  'stage.inDiscussion': 'Хэлэлцэж буй',
  'stage.secured': 'Баталгаажсан',
  'stage.toBeSecured': 'Баталгаажуулахаар',
  'stage.comingSoon': 'Удахгүй',
  'status.secured': 'Баталгаажсан',
  'status.inProgress': 'Явагдаж буй',
  'status.inDiscussion': 'Хэлэлцэж буй',
  'status.planned': 'Төлөвлөсөн',
  'status.atIssuance': 'Гаргалтын үед даалгана',
  'status.toBeCommissioned': 'Даалгах ёстой',
  'status.designStage': 'Зураг төслийн үе шат',
  'status.afterOperations': 'Үйл ажиллагаа эхэлсний дараа даалгана',
  'status.provisional': 'Түр сонгосон',
  'geo.mongolia': 'Монгол',
  'commodity.silicon': 'Цахиур',
  'commodity.lithium': 'Лити',
  'commodity.rareEarth': 'Ховор шороон элемент',
  'commodity.tba': 'Дараа зарлана',
  'proj.tsagaan.name': 'Цагаан Толгой стратегийн эрдэс',
  'proj.tsagaan.summary':
      'MPC-ийн дамжлагын анхны жишиг хөрөнгө. Хөгжүүлэлт, олборлолт, нийлүүлэлтийн манлайлал хэлэлцэгдэж байна.',
  'proj.tsagaan.desc':
      'MPC гаргалтын стандартын анхны жишиг тохиолдол. Хөгжүүлэлт, олборлолт, нийлүүлэлтийн манлайлал хэлэлцэгдэж байгаа бөгөөд онлайн гаргалтаас өмнө оффтэйк бүтэц болон бие даасан үйл ажиллагааны аудитыг даалгана. Нөөцийн хэмжээ, агуулгыг бие даасан Competent Person гарын үсэгтэй тайлангаар баталгаажуулах хүртэл нийтлэхгүй.',
  'proj.additional.name': 'Нэмэлт стратегийн нөөц',
  'proj.additional.summary': 'Хэлэлцээрт. Дэлгэрэнгүйг дараа нийтэлнэ.',
  'proj.additional.desc':
      'Нэмэлт стратегийн нөөцийг хэлэлцэж байна. Хөрөнгө урагшлах тусам MPC ижил давтагдах, аудит хийх боломжтой гаргалтын стандартын дагуу бүтэц болон баталгаажуулалтын дэлгэрэнгүйг нийтэлнэ.',

  'facts.tagline':
      'Уул уурхайн нөөцийг дэлхийн капиталын зах зээлийн хэл рүү орчуулна.',
  'facts.disclosure': 'Улирлын үйл ажиллагааны тайлан, ончейн ил тод байдал.',
  'facts.plannedStandard': 'ERC-3643 · төлөвлөсөн',
  'scope.offChain': 'Off-chain',
  'scope.onChain': 'On-chain',
  'layer.resource.title': 'Нөөцийн давхарга',
  'layer.resource.detail':
      'Хайгуул, due diligence, оффтэйк бүтэц, үйл ажиллагааны түншлэл.',
  'layer.resource.brief': 'Хайгуул, due diligence',
  'layer.structuring.title': 'Бүтцийн давхарга',
  'layer.structuring.detail':
      'Мөнгөн урсгалын загвар, эрсдэлийн усан хүрхрээ, орон нутгийн нийцэл.',
  'layer.structuring.brief': 'Мөнгөн урсгал ба нийцлийн загвар',
  'layer.tokenization.title': 'Токенжуулалтын давхарга',
  'layer.tokenization.detail': 'RWA гаргалт, бүртгэл, оракл тайлан.',
  'layer.capital.title': 'Капиталын зах зээлийн давхарга',
  'layer.capital.detail':
      'Хадгалалт, OTC / биржийн арилжаа, хоёрдогч хөрвөх чадвар.',
  'layer.tokenization.brief': 'Гаргалт, бүртгэл, оракл',
  'layer.capital.brief': 'Бүртгэл ба хоёрдогч хөрвөх чадвар',
  'risk.resource.title': 'Нөөцийн эрсдэл',
  'risk.resource.detail': 'Бие даасан нөөцийн үнэлгээ (төлөвлөсөн).',
  'risk.operational.title': 'Үйл ажиллагааны эрсдэл',
  'risk.operational.detail':
      'SLA-д суурилсан үйл ажиллагааны хяналт (зураг төсөл).',
  'risk.market.title': 'Зах зээлийн эрсдэл',
  'risk.market.detail': 'Түүхий эдийн хедж механизм (төлөвлөсөн).',
  'risk.regulatory.title': 'Зохицуулалтын эрсдэл',
  'risk.regulatory.detail':
      'KYC / AML стандартыг урьдчилан хэрэглэнэ (төлөвлөсөн).',
  'partner.audit': 'Үйл ажиллагааны аудит',
  'partner.audit.detail': 'Хэлцэл тус бүрээр даалгадаг',
  'partner.tokenization': 'Токенжуулалт (ERC-3643)',
  'partner.tokenization.detail': 'Гаргалтын дэд бүтэц',
  'partner.oracle': 'Оракл тайлан',
  'partner.oracle.detail': 'Үйл ажиллагааны өгөгдөл нээлттэй болгох',
  'verify.jorc': 'JORC биет баталгаажуулалт',
  'verify.cctv': 'CCTV + AI дижитал баталгаажуулалт',
  'verify.cp': 'Бие даасан Competent Person тайлан (JORC / NI 43-101)',
  'tx.receive': 'Хүлээн авсан',
  'tx.send': 'Илгээсэн',
  'tx.allocation': 'Төслийн хуваарилалт',
  'tx.issuance': 'Гаргалт',
  'tx.from': '-с',
  'tx.to': '-д',
  'tx.status.completed': 'Дууссан',
  'tx.status.failed': 'Амжилтгүй',
  'wallet.tx.vault': 'Цагаан Толгой vault',

  'common.retry': 'Дахин оролдох',
  'common.viewAll': 'Бүгдийг харах',
  'common.pending': 'Хүлээгдэж буй',
  'common.comingSoon': 'Удахгүй',

  'onboard.enter': 'Орох',
  'onboard.b1.title': 'Бодит уул уурхайн хөрөнгө',
  'onboard.b1.body':
      'Токенжуулсан уул уурхайн төслүүд болон гаргалтын явцыг үзээрэй.',
  'onboard.b2.title': 'Загвараараа хянагдах боломжтой',
  'onboard.b2.body': 'Биет шалгалт болон ончейн ил тод байдал.',
  'onboard.b3.title': 'MPC-ээ хянах',
  'onboard.b3.body':
      'Үлдэгдэл, түүх, мэдэгдэл бүрийн нотолгоо. Төлөвлөсөн нийт 10 тэрбум.',

  'dash.balance': 'Нийт үнэ цэнэ (MPC)',
  'dash.addFunds': 'Цэнэглэх',
  'dash.demo': 'Демо',
  'dash.testnet': 'Тестнэт',
  'dash.utilityToken': 'Хэрэглээний токен',
  'dash.totalSupply': 'Төлөвлөсөн нийлүүлэлт',
  'dash.network': 'Сүлжээ',
  'dash.listing': 'Бүртгэл',
  'dash.issuer': 'Гаргагч',
  'dash.contract': 'Гэрээ',
  'onboard.badge': 'ХАДГАЛАМЖГҮЙ ХЭТЭВЧ',
  'onboard.headline': 'Хэтэвчээ өөрөө эзэмш,\nбаталгааг шалга.',
  'onboard.subhead':
      'Аюулгүй, ил тод нэг аппаас MPC төслүүд болон хөрөнгөө удирдаарай.',
  'onboard.create': 'Хэтэвч үүсгэх',
  'onboard.import': 'Хэтэвч импортлох',
  'dash.addressLoading': 'Хэтэвчийг ачаалж байна…',
  'dash.addressUnavailable': 'Хэтэвч боломжгүй',
  'dash.explorer': 'Explorer',
  'tour.balance.title': 'Таны үлдэгдэл',
  'tour.balance.body':
      'MPC-ээ эндээс хянаарай. Дүнг нуухын тулд нүд дээр дарна уу.',
  'tour.actions.title': 'Түргэн үйлдэл',
  'tour.actions.body': 'Төсөл, орлого, хэтэвч, explorer руу шууд очно.',
  'tour.projects.title': 'Уул уурхайн төслүүд',
  'tour.projects.body':
      'Токенжуулсан уул уурхайн хөрөнгө болон төлөвийг үзээрэй.',
  'tour.settings.title': 'Хэл ба тохиргоо',
  'tour.settings.body':
      'Араа дээр дарж Тохиргоог нээгээд апп-ын хэл, харагдац, профайлаа өөрчилнө үү.',
  'dash.projects': 'Уул уурхайн төслүүд',
  'dash.howItWorks': 'MPC хэрхэн ажилладаг',

  'proj.title': 'Уул уурхайн төслүүд',
  'proj.subtitle':
      'Токенжуулсан уул уурхайн төслүүд болон тэдгээрийн гаргалтын явцыг үзнэ үү.',
  'proj.none': 'Одоогоор төсөл алга',
  'proj.noneBody': 'Гаргалтын явц нийтлэгдэх бүрд төслүүдийг үзээрэй.',
  'proj.loadError': 'Төслүүдийг ачаалж чадсангүй',
  'proj.loadErrorBody':
      'Төслийн мэдээлэл түр боломжгүй байна. Таны хэтэвчид нөлөөлөхгүй.',
  'proj.loadingTitle': 'Төслүүдийг ачаалж байна',
  'proj.loadingBody':
      'Хамгийн сүүлийн төсөл болон гаргалтын мэдээллийг шалгаж байна…',
  'proj.tryAgain': 'Дахин оролдох',
  'proj.unavailable': 'Төслүүд боломжгүй байна',
  'proj.readiness': 'Гаргалтын бэлэн байдал',
  'proj.pipeline': 'Дамжлага',
  'proj.allocated': 'MPC хуваарилагдсан',
  'proj.productionTrend': 'Ойролцоо олборлолтын чиг хандлага',
  'proj.verification': 'Баталгаажуулалт',
  'proj.governance': 'Засаглал ба эрсдэл',
  'proj.partners': 'Баталгаажуулалтын сүлжээ',
  'proj.orchestrationNote':
      'MPC эдгээр байгууллагыг ажиллуулдаггүй, гэрээ тус бүрээр даалгадаг. Төлөв нь өнөөгийн байдлыг харуулна.',
  'proj.contract': 'Гэрээ',
  'proj.tokenStandard': 'Гаргалтын стандарт (төлөвлөсөн)',
  'proj.overall': 'Нийт',
  'proj.allocatedSupply': 'Хуваарилсан нийлүүлэлт',
  'proj.hold': 'Энэ хөрөнгийг хадгалах',
  'proj.notOpen': 'Хараахан нээгдээгүй',
  'proj.viewExplorer': 'Блок эксплорер дээр үзэх',
  'proj.notFound': 'Төсөл олдсонгүй',
  'proj.betaHold': 'Хадгалах урсгал энэ бета хувилбарт хараахан ороогүй байна.',

  ...mnScreensStrings,
};
