const Map<String, String> mnScreensStrings = {
  'wallet.title': 'Хэтэвч',
  'wallet.totalBalance': 'Нийт үлдэгдэл',
  'wallet.demoNotice':
      'Туршилтын хэтэвч — энэ бета хувилбарт бодит түлхүүр үүсгэх, хадгалахгүй.',
  'wallet.allocations': 'Хуваарилалт',
  'wallet.activity': 'Үйл ажиллагаа',
  'wallet.receive': 'Хүлээн авах',
  'wallet.send': 'Илгээх',
  'wallet.unallocated': 'Хуваарилаагүй',
  'wallet.noAllocations': 'Одоогоор хуваарилалт алга',
  'wallet.noAllocationsBody': 'Идэвхтэй төсөлд MPC хадгалбал энд харагдана.',
  'wallet.noTransactions': 'Одоогоор гүйлгээ алга',
  'wallet.noTransactionsBody': 'Гүйлгээнүүд энд харагдана.',
  'wallet.loading.title': 'Хэтэвч ачаалж байна',
  'wallet.loading.body': 'Үлдэгдэл болон сүүлийн үйл ажиллагааг шалгаж байна…',
  'wallet.tryAgain': 'Дахин оролдох',
  'wallet.unavailable': 'Хэтэвч боломжгүй байна',
  'wallet.unavailableBody':
      'Үлдэгдлийг ачаалж чадсангүй. Таны хэтэвч хамгаалагдсаар байна.',
  'wallet.addressCopied': 'Хаяг хуулагдлаа',
  'wallet.transfersLater': 'Шилжүүлгийн үйлдэл дараагийн үе шатанд нэмэгдэнэ.',

  'earn.title': 'Орлого',
  'earn.gatedBanner':
      'Орлогын боломжууд төлөвлөгдсөн бөгөөд бүртгэл болон эрхийн шаардлагууд батлагдах хүртэл хязгаарлагдсан.',
  'earn.status.planned': 'Төлөвлөсөн',
  'earn.rateLabel': 'Урамшууллын хувь',
  'earn.ratePending': 'Бүртгэлийн үед зарлана',
  'earn.notify': 'Мэдэгдэл авах',
  'earn.notifyToast': 'Энэ нээгдэхэд бид танд мэдэгдэнэ.',
  'earn.staking.title': 'Стейкинг',
  'earn.staking.body':
      'Уул уурхайн хөрөнгийн гаргалтыг дэмжихийн тулд MPC-г түгжинэ. Урамшууллын нөхцөлийг бүртгэлийн үед хөтөлбөр нээгдэхэд нийтэлнэ.',
  'earn.farming.title': 'Фарминг',
  'earn.farming.body':
      'Токен бүртгэгдсэний дараа MPC хөрвөх чадвар нийлүүлж, арилжааны үйл ажиллагаанаас орлого олно. Нөхцөлийг бүртгэлийн үед нийтэлнэ.',
  'earn.whyGated': 'Яагаад хараахан үгүй вэ?',
  'earn.gate.kyc.title': 'Биеийн байцаалт (KYC)',
  'earn.gate.kyc.body':
      'MPC гаргалт нь ERC-3643 стандарт дээр төлөвлөгдсөн тул орлого олоход баталгаажсан биеийн байцаалт шаардлагатай.',
  'earn.gate.listing.title': 'Нийтийн бүртгэл',
  'earn.gate.listing.body':
      'Урамшууллын хувь ба сан нь MPC бүртгэгдэх үед тогтоогдоно.',

  'settings.title': 'Тохиргоо',
  'settings.profile': 'Профайл',
  'settings.language': 'Хэл',
  'settings.appearance': 'Харагдац',
  'settings.section.preferences': 'Тохиргоо',
  'settings.section.wallet': 'Хэтэвч ба аюулгүй байдал',
  'settings.section.appInfo': 'Дэмжлэг ба хууль эрх зүй',
  'settings.needHelp': 'Тусламж хэрэгтэй юу?',
  'settings.helpSupport': 'Тусламж ба дэмжлэг',
  'settings.notify.label': 'Мэдэгдэл',
  'settings.notify.manage': 'Удирдах',
  'settings.notify.title': 'Мэдэгдэл',
  'settings.notify.transactions': 'Гүйлгээний шинэчлэлт',
  'settings.notify.transactionsBody':
      'MPC илгээх, хүлээн авах статусын өөрчлөлт.',
  'settings.notify.security': 'Аюулгүй байдлын анхааруулга',
  'settings.notify.securityBody':
      'PIN, сэргээлт болон төхөөрөмжийн аюулгүй байдлын үйл явдлууд.',
  'settings.notify.projects': 'Төслийн шинэчлэлт',
  'settings.notify.projectsBody':
      'Дагаж буй төслүүдийн чухал статусын өөрчлөлт.',
  'settings.security': 'Аюулгүй байдал',
  'settings.pinBiometrics': 'PIN ба биометр',
  'settings.backup': 'Нөөцлөлт ба сэргэлт',
  'settings.verifyBackup': 'Нөөцлөлт баталгаажуулах',
  'settings.about': 'MPC-ийн тухай',
  'settings.privacyNotices': 'Нууцлал ба нээлттэй эх кодын мэдэгдэл',
  'settings.rateUs': 'Бидэнд үнэлгээ өгөх',
  'settings.review': 'Үнэлгээ',
  'settings.removeWallet': 'Энэ төхөөрөмжөөс хэтэвчийг устгах',
  'lang.chooseLanguage': 'Хэл сонгох',
  'lang.applyLanguage': 'Хэл хэрэглэх',
  'lang.selected': 'Сонгосон',

  'wallet.create.title': 'Хэтэвч үүсгэх',
  'wallet.create.step0.header': 'Зөвхөн та удирдах хэтэвч',
  'wallet.create.step0.body':
      'MPC энэ төхөөрөмж дээр таны хэтэвч үүсгэнэ. Төхөөрөмжөө алдвал зөвхөн сэргээх хэллэг нь хандалтыг нөхөн сэргээх цорын ганц арга юм.',
  'wallet.create.step0.holdKeys': 'Та түлхүүрийг хадгална',
  'wallet.create.step0.holdKeysBody':
      'MPC таны хэллэгийг нөхөн сэргээх эсвэл дахин тохируулах боломжгүй.',
  'wallet.create.step0.backupOffline': 'Офлайн нөөцлөлт',
  'wallet.create.step0.backupOfflineBody':
      'Үгсийг бичиж аваад нууцаар хадгалаарай.',
  'wallet.create.step0.protectDevice': 'Төхөөрөмжийг хамгаал',
  'wallet.create.step0.protectDeviceBody':
      'PIN тохируулж, сонголтоор биометр ашиглаарай.',
  'wallet.create.step0.button': 'Шинэ хэтэвч үүсгэх',
  'wallet.create.step1.header': 'Сэргээх хэллэгийг нөөцлөх',
  'wallet.create.step1.body': 'Эдгээр 12 үгийг дарааллаар нь бичиж аваарай.',
  'wallet.create.step1.phraseLabel': 'Сэргээх хэллэг',
  'wallet.create.step1.saved': 'Үгсийг хадгаллаа',
  'wallet.create.step1.download': 'Татаж авах',
  'wallet.create.step1.copy': 'Код хуулах',
  'wallet.create.step1.warning':
      'Эдгээр үгийг хэнтэй ч хуваалцаж болохгүй. MPC дэмжлэг хэзээ ч сэргээх хэллэгийг асуухгүй.',
  'wallet.create.step1.copied':
      'Сэргээх хэллэг хуулагдлаа. Clipboard 30 секундын дараа цэвэрлэгдэнэ.',
  'wallet.create.step1.saveDigital': 'Дижитал хэлбэрээр хадгалах уу?',
  'wallet.create.step1.saveDigitalBody':
      'Хадгалсан аппликейшн эсвэл клауд үйлчилгээ таны сэргээх хэллэгийг унших боломжтой. Үгийг офлайн бичих нь илүү аюулгүй.',
  'wallet.create.step1.saveCancel': 'Болих',
  'wallet.create.step1.saveContinue': 'Үргэлжлүүлэх',
  'wallet.create.step2.header': 'Нөөцлөлтийг баталгаажуулах',
  'wallet.create.step2.body':
      'Нөөцлөлтийг баталгаажуулахын тулд хүссэн үгсийг сонгоно уу.',
  'wallet.create.step2.button': 'Нөөцлөлт баталгаажуулах',
  'wallet.create.step2.mismatchTitle': 'Үгс таарсангүй',
  'wallet.create.step2.mismatchBody':
      'Сэргээх хэллэгийг шалгаад дахин оролдоно уу. Дараагийн удаа өөр үгс асуух болно.',
  'wallet.create.step2.wordLabel': '{n}-р үг',
  'wallet.create.step2.wordHint': '{n}-р үгийг оруулах',
  'wallet.create.pin.createTitle': 'Аппын PIN үүсгэх',
  'wallet.create.pin.createBody':
      'Энэ PIN-ийг ашиглан энэ төхөөрөмж дээр MPC-г тайлна.',
  'wallet.create.pin.confirmTitle': 'PIN баталгаажуулах',
  'wallet.create.pin.confirmBody': 'Мөн 6 оронтой PIN-ийг дахин оруулна уу.',
  'wallet.create.pin.hint': 'Таны PIN зөвхөн энэ төхөөрөмжийг хамгаална.',
  'wallet.create.pin.safeTitle': 'Таны хэтэвч аюулгүй байна',
  'wallet.create.pin.safeBody':
      'Юу ч хадгалагдаагүй эсвэл өөрчлөгдөөгүй. Үргэлжлүүлэхийн тулд PIN-ийг дахин оруулна уу.',
  'wallet.create.pin.continue': 'Үргэлжлүүлэх',
  'wallet.create.pin.reEnter': 'PIN дахин оруулах',
  'wallet.create.pin.confirm': 'PIN баталгаажуулах',
  'wallet.create.pin.mismatch': 'PIN таарсангүй. Дахин оролдоно уу.',
  'wallet.create.biometric.title': 'Хэтэвчийг хамгаал',
  'wallet.create.biometric.body':
      'Биометрийн аюулгүй байдлыг нэмснээр зөвхөн та хэтэвчдээ хандах боломжтой болно',
  'wallet.create.biometric.faceId': 'Face ID / Touch ID',
  'wallet.create.biometric.recommended': 'Санал болгосон',
  'wallet.create.biometric.finish': 'Тохиргоог дуусгах',
  'wallet.create.securing.title': 'Хэтэвч үүсгэж байна',
  'wallet.create.securing.body': 'Шинэ MPC хэтэвч нэмж байна…',
  'wallet.create.securing.keepOpen': 'MPC-г нээлттэй байлга',
  'wallet.create.securing.keepOpenBody':
      'Аюулгүй байдлын шалгалт дуусах хүртэл аппыг хаах хэрэггүй.',
  'wallet.create.securing.inProgress': 'Хэтэвч хамгаалж байна…',
  'wallet.create.done.title': 'Хэтэвч үүсгэгдлээ',
  'wallet.create.done.body':
      'Таны хэтэвч хамгаалагдаж, ашиглахад бэлэн боллоо.',
  'wallet.create.done.open': 'Хэтэвч нээх',

  'wallet.import.syncing.title': 'Хэтэвч импортлож байна',
  'wallet.import.syncing.body':
      'Энэ төхөөрөмжийг хамгаалж, хэтэвчийн өгөгдлийг синхрончилж байна…',

  'wallet.secure.done.title': 'Хэтэвч хамгаалагдлаа',
  'wallet.secure.done.body':
      'Таны хэтэвч энэ төхөөрөмж болон шинэ PIN кодоор хамгаалагдсан.',

  'wallet.secure.failed.title': 'Хэтэвчийг хамгаалж чадсангүй',
  'wallet.secure.failed.body':
      'Энэ төхөөрөмж дээр хэтэвчийн өгөгдөл хадгалагдаагүй.',
  'wallet.secure.failed.deviceTitle': 'Төхөөрөмжийн аюулгүй байдал боломжгүй',
  'wallet.secure.failed.deviceBody':
      'Хадгалах сан болон тохиргоог шалгаад дахин оролдоно уу.',
  'wallet.secure.failed.retry': 'Дахин оролдох',
  'wallet.secure.failed.returnToWelcome': 'Угтах хуудас руу буцах',

  'wallet.import.title': 'Хэтэвч оруулах',
  'wallet.import.secure': 'Хэтэвч хамгаалах',
  'wallet.import.step0.header': 'Одоо байгаа хэтэвчийг сэргээх',
  'wallet.import.step0.body': 'Сэргээх хэллэгийг оруулахаас өмнө:',
  'wallet.import.step0.keepPrivate': 'Нууцаар байлга',
  'wallet.import.step0.keepPrivateBody':
      'Дэлгэцийг хэн ч харахгүй байгааг баталгаажуулаарай.',
  'wallet.import.step0.enterOnly': 'Зөвхөн энд оруулна',
  'wallet.import.step0.enterOnlyBody':
      'Хэллэгийг дэмжлэгт хэзээ ч бичиж болохгүй.',
  'wallet.import.step0.stored': 'Аюулгүй хадгалагдана',
  'wallet.import.step0.storedBody':
      'MPC таны төхөөрөмж ба PIN-ээр хандалтыг хамгаална.',
  'wallet.import.step0.understand': 'Ойлголоо',
  'wallet.import.phrase.header': 'Сэргээх хэллэг оруулах',
  'wallet.import.phrase.body': 'Үгсийг зөв дарааллаар оруулна уу.',
  'wallet.import.phrase.label': 'Сэргээх хэллэг',
  'wallet.import.phrase.hint': 'Сэргээх үгсийг буулгах эсвэл бичих',
  'wallet.import.phrase.support':
      'MPC дэмжлэг хэзээ ч сэргээх хэллэгийг асуухгүй.',
  'wallet.import.phrase.errorEmpty':
      'Үргэлжлүүлэхийн тулд сэргээх хэллэгийг оруулна уу.',
  'wallet.import.phrase.errorInvalid':
      'Тэр сэргээх хэллэг хүчинтэй биш. Үгс болон тэдгээрийн дарааллыг шалгана уу.',
  'wallet.import.phrase.review': 'Хэтэвч шалгах',
  'wallet.import.address.header': 'Хэтэвч шалгах',
  'wallet.import.address.body':
      'Үргэлжлүүлэхийн өмнө хэтэвчийн хаягийг баталгаажуулна уу.',
  'wallet.import.address.label': 'ХЭТЭВЧИЙН ХАЯГ',
  'wallet.import.address.confirm': 'Энэ бол миний хэтэвч',
  'wallet.import.ready.title': 'Хэтэвч импортлогдлоо',
  'wallet.import.ready.body':
      'Таны одоо байгаа хэтэвч энэ төхөөрөмж дээр бэлэн байна.',
  'wallet.import.ready.securityComplete': 'Аюулгүй байдал дууссан',
  'wallet.import.ready.securityBody':
      'Таны сэргээх хэллэг нь өөр төхөөрөмж дээр хандалтыг сэргээх цорын ганц арга хэвээр байна.',
  'wallet.import.ready.open': 'Хэтэвч нээх',

  'wallet.secure.failed': 'Хэтэвчийг хамгаалах боломжгүй болсон',
  'wallet.secure.noData':
      'Энэ төхөөрөмж дээр хэтэвчийн өгөгдөл хадгалагдаагүй.',
  'wallet.secure.unavailable': 'Төхөөрөмжийн аюулгүй байдал боломжгүй',
  'wallet.secure.checkSettings':
      'Хадгалах сан болон төхөөрөмжийн аюулгүй байдлын тохиргоог шалгаад дахин оролдоно уу.',
  'wallet.secure.retry': 'Дахин оролдох',
  'wallet.secure.returnWelcome': 'Тавтай морил хуудас руу буцах',

  'wallet.phrase.words': '{count} үг',

  'theme.system': 'Системийн',
  'theme.light': 'Цайвар',
  'theme.dark': 'Бараан',
  'theme.apply': 'Харагдац хэрэглэх',
  'profile.title': 'Профайл',
  'profile.details': 'Бүртгэлийн мэдээлэл',
  'profile.walletAddress': 'Хаяг',

  'unlock.welcomeBack': 'Тавтай морилно уу',
  'unlock.enterPin': 'Хэтэвчийг нээхийн тулд PIN оруулна уу.',
  'unlock.forgotPin': 'PIN мартсан уу? Хэтэвч сэргээх',
  'unlock.unlock': 'Хэтэвч нээх',
  'unlock.unlocking': 'Нээж байна…',
  'unlock.useBiometrics': 'Биометр ашиглах',
  'unlock.newToMpc': 'MPC шинэ хэрэглэгч үү? ',
  'unlock.pinPrivacy': 'PIN таны төхөөрөмжөөс гарахгүй.',
  'unlock.biometricSheet.title': 'MPC-г нээх',
  'unlock.biometricSheet.body': 'Touch ID эсвэл Face ID-аар баталгаажуулна уу',
  'unlock.restore.title': 'Хэтэвчээ сэргээх үү?',
  'unlock.restore.body':
      'Төхөөрөмжийн PIN таны хэтэвчийг сэргээж чадахгүй. Сэргээх хэллэг байгаа тохиолдолд л үргэлжлүүлнэ үү.',

  'common.cancel': 'Цуцлах',
  'common.done': 'Дууссан',
  'common.continueBtn': 'Үргэлжлүүлэх',
  'common.on': 'Асаалттай',
  'common.off': 'Унтарсан',
  'common.thisDevice': 'Энэ төхөөрөмж',
  'common.gotIt': 'Ойлголоо',
  'common.pin.incomplete': 'Бүх 6 оронг оруулна уу.',
  'common.pin.incorrect': 'PIN буруу байна. Дахин оролдоно уу.',
  'common.inProgress': 'Хэрэгжиж байна',
  'receive.title': '{asset} хүлээн авах',
  'receive.unavailable': 'Хэтэвчийн хаяг боломжгүй',
  'receive.warning':
      'Энэ хаяг руу зөвхөн {asset} болон дэмжигдсэн BNB Smart Chain хөрөнгө илгээнэ үү.',
  'receive.copy': 'Хаяг хуулах',
  'receive.share': 'Хаяг хуваалцах',
  'receive.shareTemplate':
      'BNB Smart Chain дээрх миний {asset} хэтэвчийн хаяг:\n{address}',
  'receive.wrongNetwork':
      'Өөр сүлжээнээс илгээсэн хөрөнгө байнгын алдагдах магадлалтай.',
  'send.title': 'MPC илгээх',
  'send.reviewShort': 'Илгээх',
  'send.pin.title': 'PIN-ээр баталгаажуулах',
  'send.unavailableBody': 'Илгээхээсээ өмнө хэтэвчээ дахин ачаална уу.',
  'send.recipient': 'Хүлээн авагчийн хаяг',
  'send.recipientHint': 'Зөв хэтэвчийн хаягийг буулгана уу',
  'send.paste': 'БУУЛГАХ',
  'send.amount': 'Дүн',
  'send.useMax': 'Максимумыг ашиглах',
  'send.available': '{amount} боломжтой',
  'send.safety':
      'Хүлээн авагч болон сүлжээг анхааралтай шалгана уу. Блокчейн гүйлгээг буцаах боломжгүй.',
  'send.review.cta': 'Гүйлгээг шалгах',
  'send.review.sending': 'Таны илгээж байгаа',
  'send.review.to': 'Хүлээн авагч',
  'send.review.copyRecipient': 'Хүлээн авагчийн хаягийг хуулах',
  'send.review.fee': 'Сүлжээний төлбөр',
  'send.review.feeValue': '~{fee} BNB',
  'send.review.notEnoughBnb': 'BNB хүрэлцэхгүй байна',
  'send.review.note':
      'Илгээсний дараа энэ гүйлгээг өөрчлөх эсвэл цуцлах боломжгүй.',
  'send.review.confirm': 'Баталгаажуулж үргэлжлүүлэх',
  'send.review.edit': 'Гүйлгээг засах',
  'send.amountMpc': '{amount} MPC',
  'send.gas.title': 'Сүлжээний төлбөрт BNB шаардлагатай',
  'send.gas.body':
      'Энэ шилжүүлэгт ойролцоогоор {fee} BNB хэрэгтэй. Таны хэтэвчид {bnb} BNB байна.',
  'send.gas.needed': 'Шаардлагатай',
  'send.gas.note': 'Энэ төлбөрт таны MPC үлдэгдэл ашиглагдахгүй.',
  'send.gas.receive': 'BNB хүлээн авах',
  'send.gasInfo.title': 'Сүлжээний төлбөрийн таамаг',
  'send.gasInfo.body': 'Энэ бол BNB Smart Chain гүйлгээний газын төлбөр.',
  'send.pin.prompt': '6 оронтой апп PIN-ээ оруулна уу',
  'send.pin.confirm':
      'Энэ нь {amount} MPC илгээж байгаа хүн таныг баталгаажуулна.',
  'send.pin.hint': 'Апп PIN оруулна уу',
  'send.processing.title': 'Гүйлгээг боловсруулж байна',
  'send.processing.body': 'Дуустал MPC-г нээлттэй үлдээнэ үү.',
  'send.success.title': 'Гүйлгээ илгээгдлээ',
  'send.success.headline': 'MPC илгээгдлээ',
  'send.success.body': '{amount} MPC {address}-руу илгээгдлээ.',
  'send.success.status': 'Төлөв',
  'send.success.pending': 'Баталгаажуулалт хүлээж байна',
  'send.success.view': 'Гүйлгээг харах',
  'send.success.back': 'Хэтэвч рүү буцах',
  'send.failure.title': 'Гүйлгээ илгээгдээгүй',
  'send.failure.body':
      'Таны үлдэгдэл өөрчлөгдөөгүй. Холболтоо шалгаад дахин оролдоно уу.',
  'send.failure.retry': 'Дахин оролдох',
  'send.failure.cancel': 'Шилжүүлгийг цуцлах',
  'send.error.address': 'Зөв BNB Smart Chain хаяг оруулна уу.',
  'send.error.self': 'Энэ таны өөрийн хэтэвчийн хаяг байна.',
  'send.error.zero': 'Тэгээс их дүн оруулна уу.',
  'send.error.balance': 'Танд зөвхөн {amount} хуваарилаагүй MPC байна.',
  'tx.details.title': 'Гүйлгээний дэлгэрэнгүй',
  'tx.details.status': 'Төлөв',
  'tx.details.from': 'Илгээгч',
  'tx.details.to': 'Хүлээн авагч',
  'tx.details.vault': 'Төслийн хөмрөг',
  'tx.details.date': 'Огноо',
  'tx.details.hash': 'Гүйлгээний хэш',
  'tx.status.submitted': 'Илгээгдсэн',
  'tx.status.pending': 'Хүлээж байгаа',
  'tx.status.confirmed': 'Баталгаажсан',

  'settings.remove.title': 'Хэтэвчийг устгах уу?',
  'settings.remove.body':
      'Энэ нь төхөөрөмжөөс хэтэвчийн хандалт болон PIN-ийг устгана. Хэтэвчээ сэргээхийн тулд сэргээх хэллэг хэрэгтэй.',
  'settings.remove.type': 'Үргэлжлүүлэхийн тулд REMOVE гэж бичнэ үү.',
  'settings.remove.keep': 'Хэтэвчийг хадгалах',
  'settings.remove.confirm': 'Төхөөрөмжөөс устгах',
  'settings.security.title': 'Аюулгүй байдал',
  'settings.security.access': 'Хандалт',
  'settings.security.changePin': 'Апп PIN солих',
  'settings.security.pinDigits': '6 орон',
  'settings.security.biometrics': 'Биометр түгжээ тайлах',
  'settings.security.devices': 'Төхөөрөмжүүд',
  'settings.security.connectedDevices': 'Холбогдсон төхөөрөмж',
  'settings.security.activeNetwork': 'Идэвхтэй сүлжээ',
  'settings.security.chainNote':
      'Чейн ID {chainId} · MPC гүйлгээний төлбөрт BNB ашигладаг.',
  'settings.security.contract': 'MPC гэрээ',
  'settings.bio.enrol':
      'Эхлээд төхөөрөмжийн тохиргоонд хурууны хээ эсвэл нүүрээ бүртгүүлнэ үү.',
  'settings.bio.unsupported':
      'Энэ төхөөрөмж биометр түгжээ тайлалт дэмждэггүй.',
  'settings.bio.authReason': 'Биометр түгжээг идэвхжүүлэхийг баталгаажуулна уу',
  'settings.bio.locked':
      'Төхөөрөмж биометрийг түр хаасан байна. Дараа оролдоно уу.',
  'settings.bio.unavailable': 'Одоо биометр түгжээ тайлах боломжгүй байна.',
  'settings.privacy.label': 'Нууцлал',
  'settings.support.title': 'Тусламж ба дэмжлэг',
  'settings.support.getHelp': 'Тусламж авах',
  'settings.support.contact': 'Холбоо барих',
  'settings.support.contactSupport': 'Дэмжлэгт хандах',
  'settings.support.report': 'Асуудал мэдэгдэх',
  'settings.faq.recovery': 'Хэтэвч тохируулга ба сэргэлт',
  'settings.faq.sending': 'MPC илгээх ба хүлээн авах',
  'settings.faq.sendingTitle': 'Илгээх ба хүлээн авах',
  'settings.faq.fees': 'Сүлжээний төлбөр',
  'settings.faq.security': 'Аюулгүй байдал ба залилан',
  'settings.recovery.title': 'Сэргээх хэллэг',
  'settings.recovery.notVerified': 'Нөөцлөлт баталгаажаагүй',
  'settings.recovery.notVerifiedBody':
      'Хэллэгийг зөв хадгалсныг баталгаажуулна уу.',
  'settings.recovery.controls': 'Таны сэргээх хэллэг хэтэвчийг удирдана',
  'settings.recovery.neverShare':
      'Хэзээ ч хуваалцаж болохгүй. MPC дэмжлэг үүнийг хэзээ ч асуухгүй.',
  'settings.recovery.view': 'Сэргээх хэллэгийг харах',
  'settings.recovery.verify': 'Нөөцлөлтөө баталгаажуулах',
  'settings.recovery.verifiedTitle': 'Нөөцлөлт баталгаажсан',
  'settings.verify.title': 'Нөөцлөлт баталгаажуулах',
  'settings.verify.body': 'Сэргээх хэллэгийн гурван үгийг баталгаажуулна уу.',
  'settings.verify.local': 'Энэ шалгалт таны төхөөрөмж дээр үлдэнэ.',
  'settings.verify.word': '{n}-р үг',
  'settings.verify.hint': '{n}-р үгийг оруулах',
  'settings.verify.stored': 'Хэллэгийг хувийн, офлайн газар хадгаллаа.',
  'settings.verify.mark': 'Нөөцлөлтийг баталгаажсан гэж тэмдэглэх',
  'settings.verify.wrong': 'Эдгээр үг сэргээх хэллэгтэй таарахгүй байна.',
  'settings.verify.unavailable':
      'Нөөцлөлтийг зөвхөн хэтэвч үүсгэсэн эсвэл импортлосон төхөөрөмж дээр баталгаажуулж болно.',
  'settings.verified.headline': 'Хэтэвчийн нөөцлөлт дууслаа',
  'settings.verified.body':
      'Таны сэргээх хэллэг баталгаажлаа. Офлайн хуулбараа нууцлагдмал, аюулгүй хадгална уу.',
  'settings.reveal.title': 'Таныг баталгаажуулах',
  'settings.reveal.subtitle': 'Апп PIN оруулна уу',
  'settings.reveal.privacyNote':
      'Хэн ч таны дэлгэцийг харахгүй байгааг шалгана уу.',
  'settings.reveal.pinLabel': 'Апп PIN',
  'settings.reveal.cta': 'Хэллэгийг харах',
  'settings.reveal.warning':
      'Үүнийг мэдэгдэл, вэбсайт эсвэл дэмжлэгийн чатад хуулж болохгүй.',
  'settings.reveal.stored': 'Аюулгүй хадгаллаа',
  'settings.reveal.unavailable':
      'Энэ төхөөрөмж дээр сэргээх хэллэг хадгалагдаагүй.',
  'settings.reveal.appBarTitle': 'Сэргээх хэллэгийг харуулах',
  'settings.reveal.attentionTitle': 'Анхаар',
  'settings.reveal.attentionBody':
      'Сэргээх хэллэгийг харахаас өмнө дараахыг анхааралтай уншина уу.',
  'settings.reveal.fullAccessTitle': 'Бүрэн хандалт',
  'settings.reveal.fullAccessBody':
      'Энэ сэргээх хэллэг нь таны хэтэвчид бүрэн хандах эрх олгоно.',
  'settings.reveal.keepToYourselfTitle': 'Зөвхөн өөрөө мэдэж байх',
  'settings.reveal.keepToYourselfBody':
      'Энэ хэллэгийг хэнд ч, тэр дундаа дэмжлэгийн багт ч бүү илгээ.',
  'settings.reveal.storedSecurelyTitle': 'Аюулгүй хадгалах',
  'settings.reveal.storedSecurelyBody':
      'Үүнийг вэбсайт, маягт эсвэл зурваст хэзээ ч бүү бич.',
  'settings.reveal.continueWithPin': 'PIN-ээр үргэлжлүүлэх',
  'settings.reveal.pinTitle': '6 оронтой аппын PIN-ээ оруулна уу',
  'settings.reveal.pinHelper': 'Аппын PIN оруулах',
  'settings.reveal.verifyPin': 'PIN баталгаажуулах',
  'settings.reveal.phraseBody':
      'Эдгээр үгсийг дараалалд нь бичиж, офлайнаар хадгална уу.',
  'settings.reveal.noScreenshot': 'Дэлгэцийн зураг бүү авна уу.',
  'settings.reveal.writtenDown': 'Би бичиж авсан',
  'wallet.import.biometric.finish': 'Импортыг дуусгах',
  'settings.about.title': 'Global MPC-ийн тухай',
  'settings.about.tagline': 'MPC хэтэвч суулгасан мобайл DApp',
  'settings.about.version': 'Хувилбар {v}',
  'settings.about.terms': 'Ашиглах нөхцөл',
  'settings.about.privacy': 'Нууцлалын бодлого',
  'settings.about.licences': 'Нээлттэй эхийн лицензүүд',
  'settings.about.website': 'Вэбсайт',
  'settings.legal.title': 'Нууцлал ба мэдэгдэл',
  'settings.legal.identity': 'Хэтэвчийн танилт',
  'settings.legal.identityValue': 'Зөвхөн нээлттэй хаяг',
  'settings.legal.openSource': 'Нээлттэй эх',
  'settings.legal.review': 'Харах',
  'settings.legal.ack': 'Гуравдагч талуудын мэдэгдэл',
  'settings.pin.current': 'Одоогийн PIN',
  'settings.pin.new': 'Шинэ PIN',
  'settings.pin.confirmLabel': 'Шинэ PIN баталгаажуулах',
  'settings.pin.intro':
      'Одоогийн PIN-ээ баталгаажуулаад шинэ 6 оронтой PIN сонгоно уу.',
  'settings.pin.updateCta': 'PIN шинэчлэх',
  'settings.pin.updating': 'Шинэчилж байна…',
  'settings.pin.updated': 'Апп PIN шинэчлэгдлээ',
  'settings.pin.mismatch': 'PIN таарахгүй байна. Дахин оролдоно уу.',
  'notif.title': 'Мэдэгдэл',
  'notif.markAllRead': 'Бүгдийг уншсан',
  'notif.filter.all': 'Бүгд',
  'notif.filter.projects': 'Төслүүд',
  'notif.filter.security': 'Аюулгүй байдал',
  'notif.today': 'Өнөөдөр',
  'notif.yesterday': 'Өчигдөр',
  'notif.empty.title': 'Бүгдийг үзсэн байна',
  'notif.empty.body':
      'Төсөл, токен болон аюулгүй байдлын шинэчлэлүүд энд харагдана.',
  'notif.daysAgo': '{count} өдрийн өмнө',
  'notif.filterEmpty': 'Одоогоор мэдэгдэл алга.',
  'notif.tx.received.title': 'MPC хүлээн авлаа',
  'notif.tx.received.body': 'Та {amount} MPC хүлээн авлаа.',
  'notif.tx.incoming.title': 'Ирж буй MPC',
  'notif.tx.incoming.body': '{amount} MPC таны хэтэвч рүү илгээгдэж байна.',
  'notif.tx.sent.title': 'Шилжүүлэг баталгаажлаа',
  'notif.tx.sent.body': 'Таны {amount} MPC шилжүүлэг баталгаажлаа.',
  'notif.tx.failed.title': 'Шилжүүлэг амжилтгүй',
  'notif.tx.failed.body': 'Таны {amount} MPC шилжүүлэг хийгдсэнгүй.',
  'notif.sec.lockout.title': 'PIN оруулалт түр зогслоо',
  'notif.sec.lockout.body':
      'Энэ төхөөрөмж дээр буруу PIN хэт олон удаа оруулсан.',
  'notif.sec.pinChanged.title': 'Аппын PIN солигдлоо',
  'notif.sec.pinChanged.body': 'Энэ төхөөрөмжийн аппын PIN солигдлоо.',
  'notif.sec.phraseViewed.title': 'Сэргээх хэллэгийг харлаа',
  'notif.sec.phraseViewed.body':
      'Таны сэргээх хэллэг энэ төхөөрөмж дээр харагдлаа.',
  'notif.sec.biometricsOn.title': 'Биометр түгжээ тайлалт асаалаа',
  'notif.sec.biometricsOn.body':
      'Энэ хэтэвчийн биометр түгжээ тайлалтыг асаалаа.',
  'notif.sec.biometricsOff.title': 'Биометр түгжээ тайлалт унтраалаа',
  'notif.sec.biometricsOff.body':
      'Энэ хэтэвчийн биометр түгжээ тайлалтыг унтраалаа.',
};
