// GENERATED-STRUCTURE, HAND-TRANSLATED CONTENT.
// Chinese Simplified (中文) translations for the MPC app.
// Native review recommended before store release.
// Keys must stay in sync with en.dart (the source of truth).

const Map<String, String> zhStrings = {
  'app.category': '矿业 RWA 基础设施',
  'app.tagline': '将真实矿业资产带上链，可投资。从蒙古开始。',
  'app.trust': '诚信本身就是信任资本。',

  'nav.home': '首页',
  'nav.projects': '项目',
  'nav.earn': '赚币',
  'nav.wallet': '钱包',
  'stage.inDiscussion': '洽谈中',
  'stage.secured': '已确保',
  'stage.toBeSecured': '待确保',
  'stage.comingSoon': '即将推出',
  'status.secured': '已确保',
  'status.inProgress': '进行中',
  'status.inDiscussion': '讨论中',
  'status.planned': '计划中',
  'status.atIssuance': '发行时委托',
  'status.toBeCommissioned': '待委托',
  'status.designStage': '设计阶段',
  'status.afterOperations': '运营开始后委托',
  'status.provisional': '暂定选用',
  'geo.mongolia': '蒙古',
  'commodity.silicon': '硅',
  'commodity.lithium': '锂',
  'commodity.rareEarth': '稀土元素',
  'commodity.tba': '待公布',
  'proj.tsagaan.name': '查干陶勒盖战略矿产',
  'proj.tsagaan.summary': 'MPC 管线中的首个参考资产。开发、生产与供应主导权正在洽谈中。',
  'proj.tsagaan.desc':
      'MPC 发行标准的首个参考案例。开发、生产与供应主导权正在洽谈中，将在链上发行前委托承购结构设计与独立运营审计。资源量与品位在获得独立合资格人签署报告确认前不予公布。',
  'proj.additional.name': '其他战略资源',
  'proj.additional.summary': '洽谈中。详情待公布。',
  'proj.additional.desc': '正在讨论另一项战略资源。随着资产推进，MPC 将按照同样可重复、可审计的发行标准公布结构化与核验细节。',

  'facts.tagline': '将蒙古矿业资源翻译成全球资本市场的语言。',
  'facts.disclosure': '季度运营报告与链上披露。',
  'facts.plannedStandard': 'ERC-3643 · 计划中',
  'scope.offChain': '链下',
  'scope.onChain': '链上',
  'layer.resource.title': '资源层',
  'layer.resource.detail': '勘探、尽职调查、承购结构化与运营合作。',
  'layer.structuring.title': '结构化层',
  'layer.structuring.detail': '现金流建模、风险瀑布与本地合规。',
  'layer.tokenization.title': '代币化层',
  'layer.tokenization.detail': 'RWA 发行、登记与预言机报告。',
  'layer.capital.title': '资本市场层',
  'layer.capital.detail': '托管、OTC / 交易所交易与二级流动性。',
  'risk.resource.title': '资源风险',
  'risk.resource.detail': '独立储量评估（计划中）。',
  'risk.operational.title': '运营风险',
  'risk.operational.detail': '基于 SLA 的运营控制（设计阶段）。',
  'risk.market.title': '市场风险',
  'risk.market.detail': '大宗商品对冲机制（计划中）。',
  'risk.regulatory.title': '监管风险',
  'risk.regulatory.detail': 'KYC / AML 标准预先适用（计划中）。',
  'partner.audit': '运营审计',
  'partner.tokenization': '代币化 (ERC-3643)',
  'partner.oracle': '预言机报告',
  'verify.jorc': 'JORC 实物核验',
  'verify.cctv': 'CCTV + AI 数字核验',
  'verify.cp': '独立合资格人报告 (JORC / NI 43-101)',
  'tx.receive': '已收到',
  'tx.send': '已发送',
  'tx.allocation': '项目分配',
  'tx.issuance': '发行',
  'wallet.tx.vault': '查干陶勒盖金库',

  'common.retry': '重试',
  'common.viewAll': '查看全部',
  'common.pending': '待定',
  'common.comingSoon': '即将推出',

  'onboard.enter': '进入',
  'onboard.b1.title': '真实矿业资产',
  'onboard.b1.body': '浏览蒙古矿业项目及其发行进度。',
  'onboard.b2.title': '设计即可审计',
  'onboard.b2.body': '实物核验，配合链上披露。',
  'onboard.b3.title': '追踪你的 MPC',
  'onboard.b3.body': '余额与历史，每项声明均有依据。总供应量 100 亿。',

  'dash.balance': '预估总价值 (MPC)',
  'dash.addFunds': '充值',
  'dash.demo': '演示',
  'dash.testnet': '测试网',
  'dash.utilityToken': '实用型代币',
  'dash.totalSupply': '总供应量',
  'dash.network': '网络',
  'dash.listing': '上市',
  'dash.issuer': '发行方',
  'dash.contract': '合约',
  'onboard.badge': '非托管钱包',
  'onboard.headline': '自己掌管钱包，\n用凭证验证。',
  'onboard.subhead': '在一个安全、透明的应用中管理 MPC 项目与您的资产。',
  'onboard.create': '创建钱包',
  'onboard.import': '导入钱包',
  'dash.addressLoading': '正在加载钱包…',
  'dash.addressUnavailable': '钱包不可用',
  'dash.explorer': '区块浏览器',
  'tour.balance.title': '我的余额',
  'tour.balance.body': '在此追踪您的 MPC。点击眼睛图标可隐藏金额。',
  'tour.actions.title': '快捷操作',
  'tour.actions.body': '快速前往项目、赚币、钱包或区块浏览器。',
  'tour.projects.title': '矿业项目',
  'tour.projects.body': '浏览已代币化的蒙古矿业资产及其状态。',
  'tour.settings.title': '语言与设置',
  'tour.settings.body': '点击齿轮图标打开设置，即可更改应用语言、主题和个人资料。',
  'dash.projects': '矿业项目',
  'dash.howItWorks': 'MPC 运作方式',

  'proj.title': '矿业项目',
  'proj.none': '暂无项目',
  'proj.loadError': '无法加载项目',
  'proj.unavailable': '项目不可用',
  'proj.readiness': '发行准备度',
  'proj.pipeline': '发行进程',
  'proj.allocated': 'MPC 已分配',
  'proj.productionTrend': '预期产量趋势',
  'proj.verification': '核验',
  'proj.governance': '治理与风险',
  'proj.partners': '核验网络',
  'proj.orchestrationNote': 'MPC 按交易委托这些机构，而非雇佣。状态反映各方目前所处阶段。',
  'proj.contract': '合约',
  'proj.tokenStandard': '计划发行标准',
  'proj.overall': '总体',
  'proj.allocatedSupply': '已分配供应量',
  'proj.hold': '持有该资产',
  'proj.notOpen': '尚未开放',
  'proj.viewExplorer': '在区块浏览器中查看',
  'proj.notFound': '未找到项目',
  'proj.betaHold': '持有功能尚未包含在此测试版中。',

  'wallet.title': '钱包',
  'wallet.totalBalance': '总余额',
  'wallet.demoNotice': '演示钱包 — 此测试版不会生成或存储真实密钥。',
  'wallet.allocations': '分配',
  'wallet.activity': '活动记录',
  'wallet.receive': '接收',
  'wallet.send': '发送',
  'wallet.unallocated': '未分配',
  'wallet.noAllocations': '暂无分配',
  'wallet.noAllocationsBody': '在进行中的矿业项目中持有 MPC 后将在此显示。',
  'wallet.unavailable': '钱包不可用',
  'wallet.addressCopied': '地址已复制',
  'wallet.transfersLater': '转账功能将在后续版本中推出。',

  'earn.title': '赚币',
  'earn.gatedBanner': '赚币功能尚未上线。质押与流动性挖矿仅在上市并完成身份验证（KYC）后开放。目前没有可展示的收益率。',
  'earn.status.planned': '计划中',
  'earn.rateLabel': '奖励率',
  'earn.ratePending': '上市时公布',
  'earn.notify': '提醒我',
  'earn.notifyToast': '赚币开放时我们会通知您。',
  'earn.staking.title': '质押',
  'earn.staking.body': '锁定 MPC 以支持矿业资产发行。奖励条款将在项目于上市时开放时公布。',
  'earn.farming.title': '流动性耕作',
  'earn.farming.body': 'MPC 上市后提供流动性，从交易活动中获得收益。条款将在上市时公布。',
  'earn.whyGated': '为何尚未开放？',
  'earn.gate.kyc.title': '身份验证（KYC）',
  'earn.gate.kyc.body': 'MPC 发行设计基于许可制标准 ERC-3643，因此赚币将需要经过验证的身份。',
  'earn.gate.listing.title': '公开上市',
  'earn.gate.listing.body': '奖励率与资金池将在 MPC 上市时确定。在此之前不显示任何费率。',

  'settings.title': '设置',
  'settings.profile': '个人资料',
  'settings.language': '语言',
  'settings.appearance': '外观',
  'theme.system': '跟随系统',
  'theme.light': '浅色',
  'theme.dark': '深色',
  'profile.title': '个人资料',
  'profile.details': '账户详情',
  'profile.walletAddress': '地址',
};
