const Map<String, String> zhScreensStrings = {
  'wallet.title': '钱包',
  'wallet.totalBalance': '总余额',
  'wallet.demoNotice': '演示钱包 — 此测试版不会生成或存储真实密钥。',
  'wallet.allocations': '分配',
  'wallet.activity': '活动记录',
  'wallet.receive': '接收',
  'wallet.send': '发送',
  'wallet.unallocated': '未分配',
  'wallet.noAllocations': '暂无分配',
  'wallet.noAllocationsBody': '在进行中的项目中持有 MPC 后将在此显示。',
  'wallet.noTransactions': '暂无交易记录',
  'wallet.noTransactionsBody': '交易记录将显示在此处。',
  'wallet.loading.title': '正在加载钱包',
  'wallet.loading.body': '正在核对余额与近期活动…',
  'wallet.tryAgain': '重试',
  'wallet.unavailable': '钱包不可用',
  'wallet.unavailableBody': '无法加载余额。您的钱包仍受保护。',
  'wallet.addressCopied': '地址已复制',
  'wallet.transfersLater': '转账功能将在后续版本中推出。',

  'earn.title': '赚币',
  'earn.gatedBanner': '赚币功能正在规划中，将在上市及资格要求确认后开放。',
  'earn.status.planned': '计划中',
  'earn.rateLabel': '奖励率',
  'earn.ratePending': '上市时公布',
  'earn.notify': '提醒我',
  'earn.notifyToast': '开放时我们会通知您。',
  'earn.staking.title': '质押',
  'earn.staking.body': '锁定 MPC 以支持矿业资产发行。奖励条款将在项目于上市时开放时公布。',
  'earn.farming.title': '流动性耕作',
  'earn.farming.body': 'MPC 上市后提供流动性，从交易活动中获得收益。条款将在上市时公布。',
  'earn.whyGated': '为何尚未开放？',
  'earn.gate.kyc.title': '身份验证（KYC）',
  'earn.gate.kyc.body': 'MPC 发行设计基于 ERC-3643，因此赚币将需要经过验证的身份。',
  'earn.gate.listing.title': '公开上市',
  'earn.gate.listing.body': '奖励率与资金池将在 MPC 上市时确定。',

  'settings.title': '设置',
  'settings.profile': '个人资料',
  'settings.language': '语言',
  'settings.appearance': '外观',
  'settings.section.preferences': '偏好设置',
  'settings.section.wallet': '钱包与安全',
  'settings.section.appInfo': '支持与法律信息',
  'settings.needHelp': '需要帮助？',
  'settings.helpSupport': '帮助与支持',
  'settings.notify.label': '通知',
  'settings.notify.manage': '管理',
  'settings.notify.title': '通知',
  'settings.notify.transactions': '交易更新',
  'settings.notify.transactionsBody': 'MPC 收发状态变更提醒。',
  'settings.notify.security': '安全提醒',
  'settings.notify.securityBody': 'PIN、恢复和设备安全相关事件。',
  'settings.notify.projects': '项目更新',
  'settings.notify.projectsBody': '已关注项目的重要状态变更。',
  'settings.security': '安全',
  'settings.pinBiometrics': 'PIN 与生物识别',
  'settings.backup': '备份与恢复',
  'settings.verifyBackup': '验证备份',
  'settings.about': '关于 MPC',
  'settings.privacyNotices': '隐私与开源声明',
  'settings.rateUs': '给我们评分',
  'settings.review': '评价',
  'settings.removeWallet': '从此设备移除钱包',
  'lang.chooseLanguage': '选择语言',
  'lang.applyLanguage': '应用语言',
  'lang.selected': '已选择',

  'wallet.create.title': '创建钱包',
  'wallet.create.step0.header': '完全由您掌控的钱包',
  'wallet.create.step0.body': 'MPC 在此设备上创建您的钱包。如果设备丢失，恢复短语是恢复访问的唯一方式。',
  'wallet.create.step0.holdKeys': '您持有密钥',
  'wallet.create.step0.holdKeysBody': 'MPC 无法恢复或重置您的短语。',
  'wallet.create.step0.backupOffline': '离线备份',
  'wallet.create.step0.backupOfflineBody': '将这些单词写下来并妥善保管。',
  'wallet.create.step0.protectDevice': '保护此设备',
  'wallet.create.step0.protectDeviceBody': '设置 PIN 并可选择使用生物识别。',
  'wallet.create.step0.button': '创建新钱包',
  'wallet.create.step1.header': '备份恢复短语',
  'wallet.create.step1.body': '按顺序写下这 12 个单词。',
  'wallet.create.step1.phraseLabel': '恢复短语',
  'wallet.create.step1.saved': '我已保存这些单词',
  'wallet.create.step1.download': '下载',
  'wallet.create.step1.copy': '复制代码',
  'wallet.create.step1.warning': '请勿与任何人分享这些单词。MPC 支持团队永远不会要求您提供恢复短语。',
  'wallet.create.step1.copied': '恢复短语已复制。剪贴板将在30秒后清除。',
  'wallet.create.step1.saveDigital': '以数字方式保存？',
  'wallet.create.step1.saveDigitalBody': '您保存到的任何应用或云服务都可以读取您的恢复短语。将单词离线记录更安全。',
  'wallet.create.step1.saveCancel': '取消',
  'wallet.create.step1.saveContinue': '继续',
  'wallet.create.step2.header': '验证备份',
  'wallet.create.step2.body': '选择所请求的单词以确认您的备份。',
  'wallet.create.step2.button': '验证备份',
  'wallet.create.step2.mismatchTitle': '单词不匹配',
  'wallet.create.step2.mismatchBody': '请检查您的恢复短语并重试。下次将要求不同的单词。',
  'wallet.create.step2.wordLabel': '第 {n} 个单词',
  'wallet.create.step2.wordHint': '输入第 {n} 个单词',
  'wallet.create.pin.createTitle': '创建应用 PIN',
  'wallet.create.pin.createBody': '使用此 PIN 在此设备上解锁 MPC。',
  'wallet.create.pin.confirmTitle': '确认 PIN',
  'wallet.create.pin.confirmBody': '请再次输入相同的 6 位 PIN。',
  'wallet.create.pin.hint': '您的 PIN 仅保护此设备。',
  'wallet.create.pin.safeTitle': '您的钱包仍然安全',
  'wallet.create.pin.safeBody': '没有任何内容被保存或更改。请重新输入 PIN 以继续。',
  'wallet.create.pin.continue': '继续',
  'wallet.create.pin.reEnter': '重新输入 PIN',
  'wallet.create.pin.confirm': '确认 PIN',
  'wallet.create.pin.mismatch': 'PIN 不匹配。请重试。',
  'wallet.create.biometric.title': '保护您的钱包',
  'wallet.create.biometric.body': '添加生物识别安全功能将确保只有您才能访问您的钱包',
  'wallet.create.biometric.faceId': 'Face ID / Touch ID',
  'wallet.create.biometric.recommended': '推荐',
  'wallet.create.biometric.finish': '完成设置',
  'wallet.create.securing.title': '正在创建钱包',
  'wallet.create.securing.body': '正在添加新的 MPC 钱包…',
  'wallet.create.securing.keepOpen': '请保持 MPC 打开',
  'wallet.create.securing.keepOpenBody': '请在安全检查完成前不要关闭应用。',
  'wallet.create.securing.inProgress': '正在保护钱包…',
  'wallet.create.done.title': '钱包已创建',
  'wallet.create.done.body': '您的钱包已受保护，可以使用了。',
  'wallet.create.done.open': '打开钱包',

  'wallet.import.syncing.title': '正在导入您的钱包',
  'wallet.import.syncing.body': '正在保护此设备并同步钱包数据…',

  'wallet.secure.done.title': '钱包已受保护',
  'wallet.secure.done.body': '您的钱包已由此设备和新 PIN 码保护。',

  'wallet.secure.failed.title': '无法保护钱包',
  'wallet.secure.failed.body': '此设备上未保存任何钱包数据。',
  'wallet.secure.failed.deviceTitle': '设备安全不可用',
  'wallet.secure.failed.deviceBody': '请检查存储和设备安全设置，然后重试。',
  'wallet.secure.failed.retry': '重试',
  'wallet.secure.failed.returnToWelcome': '返回欢迎页',

  'wallet.import.title': '导入钱包',
  'wallet.import.secure': '安全钱包',
  'wallet.import.step0.header': '恢复现有钱包',
  'wallet.import.step0.body': '输入恢复短语前请注意：',
  'wallet.import.step0.keepPrivate': '保持私密',
  'wallet.import.step0.keepPrivateBody': '确保没有人能看到您的屏幕。',
  'wallet.import.step0.enterOnly': '仅在此处输入',
  'wallet.import.step0.enterOnlyBody': '请勿将您的短语发送给支持团队。',
  'wallet.import.step0.stored': '安全存储',
  'wallet.import.step0.storedBody': 'MPC 通过您的设备和 PIN 保护访问。',
  'wallet.import.step0.understand': '我明白了',
  'wallet.import.phrase.header': '输入恢复短语',
  'wallet.import.phrase.body': '按正确顺序输入单词。',
  'wallet.import.phrase.label': '恢复短语',
  'wallet.import.phrase.hint': '粘贴或输入您的恢复单词',
  'wallet.import.phrase.support': 'MPC 支持团队永远不会要求您提供恢复短语。',
  'wallet.import.phrase.errorEmpty': '请输入您的恢复短语以继续。',
  'wallet.import.phrase.errorInvalid': '该恢复短语无效。请检查单词及其顺序。',
  'wallet.import.phrase.review': '查看钱包',
  'wallet.import.address.header': '查看钱包',
  'wallet.import.address.body': '继续前请确认钱包地址。',
  'wallet.import.address.label': '钱包地址',
  'wallet.import.address.confirm': '这是我的钱包',
  'wallet.import.ready.title': '钱包已导入',
  'wallet.import.ready.body': '您现有的钱包已在此设备上准备就绪。',
  'wallet.import.ready.securityComplete': '安全完成',
  'wallet.import.ready.securityBody': '您的恢复短语仍是在另一台设备上恢复访问的唯一方式。',
  'wallet.import.ready.open': '打开钱包',

  'wallet.secure.failed': '无法保护钱包',
  'wallet.secure.noData': '此设备上没有保存钱包数据。',
  'wallet.secure.unavailable': '设备安全不可用',
  'wallet.secure.checkSettings': '请检查存储和设备安全设置，然后重试。',
  'wallet.secure.retry': '重试',
  'wallet.secure.returnWelcome': '返回欢迎页面',

  'wallet.phrase.words': '{count} 个单词',

  'theme.system': '跟随系统',
  'theme.light': '浅色',
  'theme.dark': '深色',
  'theme.apply': '应用外观',
  'profile.title': '个人资料',
  'profile.details': '账户详情',
  'profile.walletAddress': '地址',

  'unlock.welcomeBack': '欢迎回来',
  'unlock.enterPin': '输入 PIN 以解锁钱包。',
  'unlock.forgotPin': '忘记 PIN？恢复钱包',
  'unlock.unlock': '解锁钱包',
  'unlock.unlocking': '解锁中…',
  'unlock.useBiometrics': '使用生物识别',
  'unlock.newToMpc': 'MPC 新用户？',
  'unlock.pinPrivacy': '您的 PIN 绝不会离开此设备。',
  'unlock.biometricSheet.title': '解锁 MPC',
  'unlock.biometricSheet.body': '使用 Touch ID 或 Face ID 确认',
  'unlock.restore.title': '恢复钱包？',
  'unlock.restore.body': '设备 PIN 无法恢复您的钱包。仅在您拥有恢复短语时继续。',

  'common.cancel': '取消',
  'common.done': '完成',
  'common.continueBtn': '继续',
  'common.on': '开启',
  'common.off': '关闭',
  'common.thisDevice': '本设备',
  'common.gotIt': '知道了',
  'common.pin.incomplete': '请输入全部 6 位数字。',
  'common.pin.incorrect': 'PIN 码错误，请重试。',
  'common.inProgress': '进行中',
  'receive.title': '接收 {asset}',
  'receive.unavailable': '钱包地址不可用',
  'receive.warning': '请仅向此地址发送 {asset} 及支持的 BNB Smart Chain 资产。',
  'receive.copy': '复制地址',
  'receive.share': '分享地址',
  'receive.shareTemplate': '我的 BNB Smart Chain {asset} 钱包地址:\n{address}',
  'receive.wrongNetwork': '从其他网络发送的资产可能永久丢失。',
  'send.title': '发送 MPC',
  'send.reviewShort': '发送',
  'send.pin.title': '使用 PIN 确认',
  'send.unavailableBody': '发送前请重新加载钱包。',
  'send.recipient': '收款地址',
  'send.recipientHint': '请粘贴有效的钱包地址',
  'send.paste': '粘贴',
  'send.amount': '数量',
  'send.useMax': '使用最大值',
  'send.available': '可用 {amount}',
  'send.safety': '请仔细核对收款方和网络。区块链交易无法撤销。',
  'send.review.cta': '确认交易',
  'send.review.sending': '您正在发送',
  'send.review.to': '收款方',
  'send.review.copyRecipient': '复制收款地址',
  'send.review.fee': '网络手续费',
  'send.review.feeValue': '~{fee} BNB',
  'send.review.notEnoughBnb': 'BNB 不足',
  'send.review.note': '交易提交后无法更改或取消。',
  'send.review.confirm': '确认并继续',
  'send.review.edit': '编辑交易',
  'send.amountMpc': '{amount} MPC',
  'send.gas.title': '网络手续费需要 BNB',
  'send.gas.body': '此转账大约需要 {fee} BNB。您的钱包有 {bnb} BNB。',
  'send.gas.needed': '所需',
  'send.gas.note': '此手续费不会使用您的 MPC 余额。',
  'send.gas.receive': '接收 BNB',
  'send.gasInfo.title': '预估网络手续费',
  'send.gasInfo.body': '这是 BNB Smart Chain 转账的 Gas 费用。',
  'send.pin.prompt': '请输入您的 6 位应用 PIN 码',
  'send.pin.confirm': '这将确认是您本人发送 {amount} MPC。',
  'send.pin.hint': '输入应用 PIN 码',
  'send.processing.title': '正在处理交易',
  'send.processing.body': '完成前请保持 MPC 开启。',
  'send.success.title': '交易已提交',
  'send.success.headline': 'MPC 已发送',
  'send.success.body': '{amount} MPC 已提交至 {address}。',
  'send.success.status': '状态',
  'send.success.pending': '待确认',
  'send.success.view': '查看交易',
  'send.success.back': '返回钱包',
  'send.failure.title': '交易未发送',
  'send.failure.body': '您的余额未发生变化。请检查网络连接后重试。',
  'send.failure.retry': '重试',
  'send.failure.cancel': '取消转账',
  'send.error.address': '请输入有效的 BNB Smart Chain 地址。',
  'send.error.self': '这是您自己的钱包地址。',
  'send.error.zero': '请输入大于 0 的金额。',
  'send.error.balance': '您仅有 {amount} 未分配的 MPC。',
  'tx.details.title': '交易详情',
  'tx.details.status': '状态',
  'tx.details.from': '发送方',
  'tx.details.to': '收款方',
  'tx.details.vault': '项目金库',
  'tx.details.date': '日期',
  'tx.details.hash': '交易哈希',
  'tx.status.submitted': '已提交',
  'tx.status.pending': '待处理',
  'tx.status.confirmed': '已确认',

  'settings.remove.title': '移除钱包？',
  'settings.remove.body': '这将从本设备移除钱包访问权限和 PIN 码。您需要恢复短语才能恢复钱包。',
  'settings.remove.type': '输入 REMOVE 以继续。',
  'settings.remove.keep': '保留钱包',
  'settings.remove.confirm': '从设备移除',
  'settings.security.title': '安全',
  'settings.security.access': '访问',
  'settings.security.changePin': '更改应用 PIN 码',
  'settings.security.pinDigits': '6 位数字',
  'settings.security.biometrics': '生物识别解锁',
  'settings.security.devices': '设备',
  'settings.security.connectedDevices': '已连接设备',
  'settings.security.activeNetwork': '当前网络',
  'settings.security.chainNote': '链 ID {chainId} · MPC 转账使用 BNB 支付手续费。',
  'settings.security.contract': 'MPC 合约',
  'settings.bio.enrol': '请先在设备设置中录入指纹或面容。',
  'settings.bio.unsupported': '此设备不支持生物识别解锁。',
  'settings.bio.authReason': '确认以启用生物识别解锁',
  'settings.bio.locked': '生物识别已被设备暂时锁定，请稍后重试。',
  'settings.bio.unavailable': '生物识别解锁当前不可用。',
  'settings.privacy.label': '隐私',
  'settings.support.title': '帮助与支持',
  'settings.support.getHelp': '获取帮助',
  'settings.support.contact': '联系',
  'settings.support.contactSupport': '联系支持团队',
  'settings.support.report': '报告问题',
  'settings.faq.recovery': '钱包设置与恢复',
  'settings.faq.sending': '发送与接收 MPC',
  'settings.faq.sendingTitle': '发送与接收',
  'settings.faq.fees': '网络手续费',
  'settings.faq.security': '安全与诈骗',
  'settings.recovery.title': '恢复短语',
  'settings.recovery.notVerified': '备份未验证',
  'settings.recovery.notVerifiedBody': '请验证您已妥善保存短语。',
  'settings.recovery.controls': '您的恢复短语掌控着您的钱包',
  'settings.recovery.neverShare': '切勿分享。MPC 支持团队绝不会索要此短语。',
  'settings.recovery.view': '查看恢复短语',
  'settings.recovery.verify': '验证我的备份',
  'settings.recovery.verifiedTitle': '备份已验证',
  'settings.verify.title': '验证备份',
  'settings.verify.body': '请确认恢复短语中的三个单词。',
  'settings.verify.local': '此检查仅在您的设备上进行。',
  'settings.verify.word': '第 {n} 个单词',
  'settings.verify.hint': '输入第 {n} 个单词',
  'settings.verify.stored': '我已将短语保存在私密的离线位置。',
  'settings.verify.mark': '标记备份为已验证',
  'settings.verify.wrong': '这些单词与您的恢复短语不匹配。',
  'settings.verify.unavailable': '备份只能在创建或导入此钱包的设备上验证。',
  'settings.verified.headline': '钱包备份完成',
  'settings.verified.body': '您的恢复短语已确认。请妥善保管您的离线副本。',
  'settings.reveal.title': '请确认是您本人',
  'settings.reveal.subtitle': '输入应用 PIN 码',
  'settings.reveal.privacyNote': '请确保无人能看到您的屏幕。',
  'settings.reveal.pinLabel': '应用 PIN 码',
  'settings.reveal.cta': '显示短语',
  'settings.reveal.warning': '切勿将此内容复制到消息、网站或客服聊天中。',
  'settings.reveal.stored': '我已安全保存',
  'settings.reveal.unavailable': '此设备上没有保存恢复短语。',
  'settings.reveal.appBarTitle': '显示恢复短语',
  'settings.reveal.attentionTitle': '注意',
  'settings.reveal.attentionBody': '查看恢复短语前，请仔细阅读以下内容。',
  'settings.reveal.fullAccessTitle': '完全访问权限',
  'settings.reveal.fullAccessBody': '此恢复短语可完全控制您的钱包。',
  'settings.reveal.keepToYourselfTitle': '请勿告知他人',
  'settings.reveal.keepToYourselfBody': '请勿将此短语发送给任何人，包括客服人员。',
  'settings.reveal.storedSecurelyTitle': '安全存放',
  'settings.reveal.storedSecurelyBody': '切勿在网站、表单或消息中输入此短语。',
  'settings.reveal.continueWithPin': '使用 PIN 继续',
  'settings.reveal.pinTitle': '请输入您的 6 位应用 PIN',
  'settings.reveal.pinHelper': '输入您的应用 PIN',
  'settings.reveal.verifyPin': '验证 PIN',
  'settings.reveal.phraseBody': '请按顺序抄写这些单词并离线保存。',
  'settings.reveal.noScreenshot': '请勿截图。',
  'settings.reveal.writtenDown': '我已抄写',
  'wallet.import.biometric.finish': '完成导入',
  'settings.about.title': '关于 Global MPC',
  'settings.about.tagline': '内置 MPC 钱包的移动 DApp',
  'settings.about.version': '版本 {v}',
  'settings.about.terms': '使用条款',
  'settings.about.privacy': '隐私政策',
  'settings.about.licences': '开源许可',
  'settings.about.website': '网站',
  'settings.legal.title': '隐私与声明',
  'settings.legal.identity': '钱包身份',
  'settings.legal.identityValue': '仅公开地址',
  'settings.legal.openSource': '开源',
  'settings.legal.review': '查看',
  'settings.legal.ack': '第三方致谢',
  'settings.pin.current': '当前 PIN 码',
  'settings.pin.new': '新 PIN 码',
  'settings.pin.confirmLabel': '确认新 PIN 码',
  'settings.pin.intro': '请确认当前 PIN 码，然后设置新的 6 位 PIN 码。',
  'settings.pin.updateCta': '更新 PIN',
  'settings.pin.updating': '更新中…',
  'settings.pin.updated': '应用 PIN 码已更新',
  'settings.pin.mismatch': '两次输入的 PIN 码不一致，请重试。',
  'notif.title': '通知',
  'notif.markAllRead': '全部已读',
  'notif.filter.all': '全部',
  'notif.filter.projects': '项目',
  'notif.filter.security': '安全',
  'notif.today': '今天',
  'notif.yesterday': '昨天',
  'notif.empty.title': '已全部查看',
  'notif.empty.body': '项目、代币和安全动态将显示在这里。',
  'notif.daysAgo': '{count} 天前',
  'notif.filterEmpty': '暂无通知。',
  'notif.tx.received.title': '已收到 MPC',
  'notif.tx.received.body': '您收到了 {amount} MPC。',
  'notif.tx.incoming.title': 'MPC 转入中',
  'notif.tx.incoming.body': '{amount} MPC 正在转入您的钱包。',
  'notif.tx.sent.title': '转账已确认',
  'notif.tx.sent.body': '您转出的 {amount} MPC 已确认。',
  'notif.tx.failed.title': '转账失败',
  'notif.tx.failed.body': '您转出的 {amount} MPC 未能完成。',
  'notif.sec.lockout.title': 'PIN 输入已暂停',
  'notif.sec.lockout.body': '此设备上错误 PIN 尝试次数过多。',
  'notif.sec.pinChanged.title': '应用 PIN 已更改',
  'notif.sec.pinChanged.body': '此设备上的应用 PIN 已更改。',
  'notif.sec.phraseViewed.title': '已查看恢复短语',
  'notif.sec.phraseViewed.body': '您的恢复短语已在此设备上显示。',
  'notif.sec.biometricsOn.title': '生物识别解锁已开启',
  'notif.sec.biometricsOn.body': '此钱包已开启生物识别解锁。',
  'notif.sec.biometricsOff.title': '生物识别解锁已关闭',
  'notif.sec.biometricsOff.body': '此钱包已关闭生物识别解锁。',
};
